// huahin.properties — shared data & i18n
// Plain ES module: PROPERTIES (sample listings), I18N (UI strings), AREAS/TYPES/FEATURES/STATUS labels.

export const LANGS = ["en", "th", "ru", "zh", "de", "no", "fr", "it"];

export const LANG_LABELS = { en: "English", th: "ไทย", ru: "Русский", zh: "中文", de: "Deutsch", no: "Norsk", fr: "Français", it: "Italiano" };

export function getLang() {
  try { return localStorage.getItem("hh_lang") || "th"; } catch (e) { return "th"; }
}
export function setLang(l) {
  try { localStorage.setItem("hh_lang", l); } catch (e) {}
  try { window.dispatchEvent(new CustomEvent("langchange", { detail: l })); } catch (e) {}
}
export function t(dict, lang, key) {
  return (dict[lang] && dict[lang][key]) ?? (dict.en && dict.en[key]) ?? key;
}

export const AREAS = [
  { id: "hua-hin", label: { en: "Hua Hin", th: "หัวหิน", ru: "Хуахин", zh: "华欣", de: "Hua Hin", no: "Hua Hin", fr: "Hua Hin", it: "Hua Hin" } },
  { id: "pranburi", label: { en: "Pranburi", th: "ปราณบุรี", ru: "Пранбури", zh: "巴蓝武里", de: "Pranburi", no: "Pranburi", fr: "Pranburi", it: "Pranburi" } },
  { id: "cha-am", label: { en: "Cha-am", th: "ชะอำ", ru: "Ча-Ам", zh: "差安", de: "Cha-am", no: "Cha-am", fr: "Cha-am", it: "Cha-am" } },
];

// Real ตำบล (sub-district) names per อำเภอ (district) — lets the lister narrow
// location further than the district-level AREAS list above. Plain Thai
// strings (not translated) since this is an internal form filter tag, not
// public multi-language display copy.
export const SUBDISTRICTS = {
  "hua-hin": ["หัวหิน", "หนองแก", "หินเหล็กไฟ", "หนองพลับ", "ทับใต้", "ห้วยสัตว์ใหญ่", "บึงนคร", "ศาลาลัย"],
  "pranburi": ["ปราณบุรี", "เขาน้อย", "ปากน้ำปราณ", "วังก์พง", "หนองตาแต้ม", "ไร่ใหม่"],
  "cha-am": ["ชะอำ", "บางเก่า", "เขาใหญ่", "ห้วยทรายเหนือ", "ไร่ใหม่พัฒนา", "ดอนขุนห้วย", "สามพระยา", "นายาง"],
};

export const TYPES = [
  { id: "villa", label: { en: "Pool Villa", th: "พูลวิลล่า", ru: "Вилла с бассейном", zh: "泳池别墅", de: "Poolvilla", no: "Bassengvilla", fr: "Villa avec piscine", it: "Villa con piscina" } },
  { id: "house", label: { en: "House", th: "บ้านเดี่ยว", ru: "Дом", zh: "独立屋", de: "Haus", no: "Hus", fr: "Maison", it: "Casa" } },
  { id: "condo", label: { en: "Condo", th: "คอนโด", ru: "Кондо", zh: "公寓", de: "Eigentumswohnung", no: "Leilighet", fr: "Condo", it: "Condominio" } },
  { id: "land", label: { en: "Land", th: "ที่ดิน", ru: "Земля", zh: "土地", de: "Grundstück", no: "Tomt", fr: "Terrain", it: "Terreno" } },
  { id: "commercial", label: { en: "Commercial", th: "เชิงพาณิชย์", ru: "Коммерция", zh: "商业地产", de: "Gewerbe", no: "Næringseiendom", fr: "Commercial", it: "Commerciale" } },
];

export const STATUS = {
  sale: { en: "For Sale", th: "ประกาศขาย", ru: "Продаётся", zh: "出售", de: "Zu verkaufen", no: "Til salgs", fr: "À vendre", it: "In vendita" },
  rent: { en: "For Rent", th: "ประกาศเช่า", ru: "В аренду", zh: "出租", de: "Zu vermieten", no: "Til leie", fr: "À louer", it: "In affitto" },
  rented: { en: "Rented", th: "เช่าแล้ว", ru: "Сдано в аренду", zh: "已出租", de: "Vermietet", no: "Utleid", fr: "Loué", it: "Affittato" },
  sold: { en: "Sold", th: "ขายแล้ว", ru: "Продано", zh: "已售", de: "Verkauft", no: "Solgt", fr: "Vendu", it: "Venduto" },
  reserved: { en: "Reserved", th: "จองแล้ว", ru: "Забронировано", zh: "已预订", de: "Reserviert", no: "Reservert", fr: "Réservé", it: "Prenotato" },
};

export const FEATURES = {
  sea_view: { en: "Sea View", th: "วิวทะเล", ru: "Вид на море", zh: "海景", de: "Meerblick", no: "Sjøutsikt", fr: "Vue mer", it: "Vista mare" },
  mountain_view: { en: "Mountain View", th: "วิวภูเขา", ru: "Вид на горы", zh: "山景", de: "Bergblick", no: "Fjellutsikt", fr: "Vue montagne", it: "Vista montagna" },
  pool: { en: "Private Pool", th: "สระว่ายน้ำส่วนตัว", ru: "Частный бассейн", zh: "私人泳池", de: "Privater Pool", no: "Privat basseng", fr: "Piscine privée", it: "Piscina privata" },
  shared_pool: { en: "Shared Pool", th: "สระว่ายน้ำส่วนกลาง", ru: "Общий бассейн", zh: "共用泳池", de: "Gemeinschaftspool", no: "Fellesbasseng", fr: "Piscine commune", it: "Piscina comune" },
  furnished: { en: "Fully Furnished", th: "เฟอร์นิเจอร์ครบ", ru: "С мебелью", zh: "全套家具", de: "Voll möbliert", no: "Fullt møblert", fr: "Entièrement meublé", it: "Completamente arredato" },
  new: { en: "New / Move-in Ready", th: "บ้านใหม่ พร้อมเข้าอยู่", ru: "Новый, готов к заселению", zh: "全新可入住", de: "Neu / Bezugsfertig", no: "Nytt / Innflytningsklart", fr: "Neuf / Prêt à emménager", it: "Nuovo / Pronto per trasferirsi" },
  beachfront: { en: "Beachfront", th: "ติดชายหาด", ru: "На берегу моря", zh: "海滨第一排", de: "Direkt am Strand", no: "Ved stranden", fr: "Front de mer", it: "Fronte mare" },
  gated: { en: "Gated Village", th: "หมู่บ้านมีระบบรักษาความปลอดภัย", ru: "Закрытый посёлок", zh: "封闭式社区", de: "Bewachte Siedlung", no: "Gjerdet boligområde", fr: "Résidence sécurisée", it: "Residence recintato" },
  quiet: { en: "Quiet Soi", th: "ซอยเงียบสงบ", ru: "Тихая улица", zh: "安静巷弄", de: "Ruhige Straße", no: "Rolig gate", fr: "Rue calme", it: "Strada tranquilla" },
  golf: { en: "Near Golf Course", th: "ใกล้สนามกอล์ฟ", ru: "Рядом с полем для гольфа", zh: "近高尔夫球场", de: "Nahe Golfplatz", no: "Nær golfbane", fr: "Près d'un golf", it: "Vicino al golf" },
  riverside: { en: "Riverside", th: "ติดริมแม่น้ำ", ru: "У реки", zh: "河畔", de: "Am Fluss", no: "Ved elven", fr: "Bord de rivière", it: "Lungofiume" },
  rental_yield: { en: "Strong Rental Yield", th: "ผลตอบแทนค่าเช่าดี", ru: "Высокая доходность аренды", zh: "租金回报高", de: "Hohe Mietrendite", no: "Høy leieavkastning", fr: "Rendement locatif élevé", it: "Alto rendimento locativo" },
  pet_friendly: { en: "Pet Friendly", th: "เลี้ยงสัตว์ได้", ru: "Можно с животными", zh: "允许宠物", de: "Haustiere erlaubt", no: "Kjæledyr tillatt", fr: "Animaux acceptés", it: "Animali ammessi" },
};

export const PROPERTIES = [
];

// Approximate centroid per zone/subdistrict — used to show a general-area
// highlight (not the exact house) on the public Property Details map, so
// browsing the site never reveals a precise pin buyers could use to bypass
// the agent. Admin's internal Property Map still plots exact-ish pins.
export const ZONE_COORDS = {
  "Khao Tao": { lat: 12.4805, lng: 99.9713 },
  "Hin Lek Fai": { lat: 12.5935, lng: 99.9430 },
  "Khao Takiab": { lat: 12.5095, lng: 99.9805 },
  "Thap Tai": { lat: 12.6010, lng: 99.9605 },
  "Soi 88": { lat: 12.5760, lng: 99.9605 },
  "Hua Hin Town": { lat: 12.5684, lng: 99.9578 },
  "Dolphin Bay": { lat: 12.2495, lng: 99.9705 },
  "Pak Nam Pran": { lat: 12.3300, lng: 99.9595 },
  "Wang Phong": { lat: 12.4205, lng: 99.9295 },
  "Pranburi Forest": { lat: 12.3605, lng: 99.9095 },
  "Sam Roi Yot": { lat: 12.2010, lng: 99.9605 },
  "Nong Chumsaeng": { lat: 12.4005, lng: 99.8895 },
  "Pranburi Beach": { lat: 12.3905, lng: 99.9655 },
  "Cha-am Beach": { lat: 12.8050, lng: 99.9700 },
  "Nong Kae": { lat: 12.7300, lng: 99.9605 },
  "Cha-am Hillside": { lat: 12.7900, lng: 99.9400 },
  "Cha-am Town": { lat: 12.8000, lng: 99.9650 },
};

export const I18N = {
  en: {
    site_name: "huahin.properties",
    nav_buy: "Buy", nav_rent: "Rent", nav_sell: "Sell / List", nav_about: "About", nav_contact: "Contact", nav_admin: "Admin",
    hero_kicker: "Hua Hin · Pranburi · Cha-am",
    hero_title_1: "Coastal living,", hero_title_2: "quietly luxurious.",
    hero_sub: "Curated pool villas, beachfront homes and land along Thailand's royal coast — for buyers, tenants and owners who expect more.",
    want_label: "I want to", buy: "Buy", rent: "Rent",
    location_label: "Location", all_zones: "All areas",
    type_label: "Property Type", any_type: "Any type",
    budget_label: "Budget", any_price: "Any price",
    search_cta: "Search Properties",
    cta_find: "Find Your Home", cta_buy: "Buy Property", cta_rent: "Rent Property", cta_list: "List Your Property", cta_contact: "Contact an Agent",
    featured_title: "Featured Properties", featured_sub: "A hand-picked selection across the coast",
    view_details: "View Details",
    areas_title: "Explore by Area",
    area_hua_hin_desc: "Thailand's original royal seaside town — beaches, golf and the historic railway.",
    area_pranburi_desc: "Wide sandy beaches and quiet land, favoured for private retreats.",
    area_cha_am_desc: "A relaxed beach town with strong rental demand and easy access to Bangkok.",
    about_title: "Why huahin.properties",
    about_body: "We are a boutique agency based in Hua Hin, working exclusively across Hua Hin, Pranburi and Cha-am. Every listing is verified in person, every owner vetted, and every buyer guided from first viewing to signed Chanote.",
    footer_rights: "All rights reserved.",
    final_cta_title: "Ready to find your Hua Hin home?", footer_tagline: "A boutique real estate agency for Hua Hin, Pranburi and Cha-am.", footer_explore: "Explore", footer_company: "Company", footer_contact: "Contact",
    share_site: "Share this site", copy_link: "Copy link", link_copied: "Link copied!",
    login_signup: "Login / Sign up", bd_short: "bd", ba_short: "ba", properties_saved: "properties saved", property_saved: "property saved",
    trust_local_title: "Local Hua Hin Expertise", trust_local_desc: "Boutique agency based on the ground in Hua Hin, Pranburi and Cha-am.",
    trust_verified_title: "Verified Listings", trust_verified_desc: "Every property is inspected and verified in person before publishing.",
    trust_lang_title: "Multilingual Service", trust_lang_desc: "Support in Thai, English, Russian, Chinese and more.",
    trust_contact_title: "Direct Contact", trust_contact_desc: "Reach an agent directly via LINE, WhatsApp or phone — no call centers.",
    listings_count: "listings",
    sort_label: "Sort", sort_newest: "Newest", sort_price_asc: "Price: Low to High", sort_price_desc: "Price: High to Low",
    view_grid: "Grid", view_list: "List",
    filters: "Filters", apply_filters: "Apply Filters", clear_filters: "Clear",
    keyword_label: "Keyword or Property Code", keyword_placeholder: "e.g. HH-101 or pool villa",
    gallery_tab_photos: "Photos", gallery_tab_video: "Video Tour", gallery_tab_360: "360° Tour", coming_soon: "coming soon",
    reviews_title: "Customer Reviews", no_reviews: "No reviews yet", reviews_unit: "reviews", reviews_sample_note: "sample data",
    no_reviews_placeholder: "No reviews yet — this space is reserved for the review system in a future version.",
    mortgage_calc_title: "Mortgage Calculator", mortgage_down_payment: "Down Payment", mortgage_loan_years: "Loan Term", years_unit: "yrs",
    mortgage_interest_rate: "Interest Rate", mortgage_monthly_payment: "Est. Monthly Payment",
    mortgage_disclaimer: "This is a basic estimate (principal + interest only, excludes fees/insurance) — not a real loan offer.",
    schedule_viewing_title: "Schedule Viewing",
    bedrooms_label: "Bedrooms", bathrooms_label: "Bathrooms", land_size_label: "Land Size", living_area_label: "Living Area", any: "Any",
    status_label: "Status", features_label: "Features",
    no_results: "No properties match your filters.",
    sqm: "sqm", per_month: "/ month",
    km_to: "km to", mini_site_label: "Mini Site",
    beach: "beach", town: "town",
    gallery_photo: "Photo",
    property_overview: "Overview", property_description: "Property Description", no_description: "No description provided yet.", property_features: "Features & Amenities", property_location: "Location", property_general_area: "General area", similar_properties: "Similar Properties",
    contact_agent: "Contact an Agent", enquiry_form: "Send an Enquiry", name_label: "Name", email_label: "Email", phone_label: "Phone", message_label: "Message", send: "Send Enquiry",
    call: "Call", whatsapp: "WhatsApp", line_app: "Line", email_cta: "Email",
    sell_title: "List Your Property", sell_sub: "Tell us about your property — for sale or for rent — and our team will get in touch within 24 hours.",
    sell_owner_name: "Your Name", sell_owner_phone: "Phone", sell_owner_email: "Email", sell_owner_line: "Line ID (optional)",
    sell_property_type: "Property Type", sell_listing_type: "Listing Type", sell_area: "Area", sell_price: "Asking Price", sell_notes: "Tell us more",
    sell_submit: "Submit Property",
    contact_title: "Contact Us", contact_sub: "Questions about buying, renting or listing in Hua Hin, Pranburi or Cha-am? We're here.",
    admin_login_title: "Admin Login", admin_username: "Username", admin_password: "Password", admin_login_cta: "Sign In",
    admin_dashboard: "Dashboard", admin_listings: "Listings", admin_total: "Total Listings", admin_for_sale: "For Sale", admin_for_rent: "For Rent", admin_sold: "Sold", admin_reserved: "Reserved", admin_new: "New This Month",
    admin_add_property: "Add Property", admin_edit: "Edit", admin_delete: "Delete", admin_search: "Search listings...",
    admin_owner_info: "Owner Info (Private)", admin_internal_notes: "Internal Notes", admin_photos: "Photos", admin_set_cover: "Set as cover", admin_save: "Save Changes", admin_saving: "Saving…", admin_save_success: "Saved successfully", admin_photos_note: "Photos save instantly on upload — no need to wait for Save Changes.", admin_cancel: "Cancel",
    admin_logout: "Log Out", admin_signed_in_as: "Signed in as Admin",
    admin_field_title: "Title", admin_field_zone: "Zone", admin_field_price: "Price (THB)",
    admin_field_land_size: "Land Size (sqm)", admin_field_living_area: "Living Area (sqm)",
    admin_field_parking: "Parking", admin_field_ownership: "Ownership",
    admin_field_distance_beach: "Distance to beach (km)", admin_field_distance_town: "Distance to town (km)",
    admin_field_pool: "Swimming pool", admin_field_furnished: "Furnished",
    admin_furnished_full: "Fully furnished", admin_furnished_partial: "Partially furnished", admin_furnished_none: "Unfurnished",
    admin_field_short_desc: "Short Description", admin_field_full_desc: "Full Description",
    admin_add_photo: "+ Add photo slot", admin_owner_disclaimer: "never shown publicly",
    admin_owner_name_ph: "Owner name", admin_owner_phone_ph: "Owner phone", admin_owner_email_ph: "Owner email", admin_owner_line_ph: "Owner Line ID",
    admin_owner_notes_ph: "Private notes about the owner",
    admin_owners_nav: "Contacts", admin_owners_title: "Owner Directory", admin_owners_sub: "Every owner and every property they've listed with us — private, admin only.",
    admin_owner_properties: "Properties", admin_view_on_map: "View on map", admin_view_edit_property: "View / Edit property",
    admin_back_to_dashboard: "← Back to Dashboard", admin_new_owner: "+ New owner", admin_owner_select: "Owner",
    admin_owner_photo1: "Owner photo / ID", admin_owner_photo2: "Contact screenshot", admin_map_link: "Map link (Google Maps URL)",
    admin_tenant_photo1: "Tenant photo / ID", admin_tenant_photo2: "Contact screenshot",
    admin_rented: "Currently Rented", admin_lease_ends: "Lease ends", admin_days_left: "days left", admin_tenant: "Tenant",
    admin_showing_rented: "Showing rented properties, soonest lease end first", admin_clear_view: "✕ Clear",
    status_rented: "Rented (occupied)", admin_lease_start: "Lease Start", admin_lease_end: "Lease End",
    admin_tenant_info: "Tenant Info", admin_tenant_select: "Tenant", admin_new_tenant: "+ New tenant",
    admin_tenant_name_ph: "Tenant name", admin_tenant_phone_ph: "Tenant phone", admin_tenant_email_ph: "Tenant email", admin_tenant_line_ph: "Tenant Line ID", admin_tenant_notes_ph: "Notes about the tenant",
    contacts_title: "Contact Directory", contacts_sub: "Owners, tenants and every property linked to them — private, admin only.",
    contacts_tab_owners: "Owners", contacts_tab_tenants: "Tenants", admin_lease_ends_col: "Lease ends",
    admin_map_title: "Property Map", admin_map_sub: "Browse the live map of Hua Hin, Pranburi and Cha-am, then click any listing below to view it on the map or open it for editing.", admin_map_note: "Real Google Maps embed above (no API key configured for custom pins in this prototype) — use the color-coded list below to browse by type and click through to a listing.", admin_map_nav: "Map",
  },
  th: {
    site_name: "huahin.properties",
    nav_buy: "ซื้อ", nav_rent: "เช่า", nav_sell: "ฝากขาย/เช่า", nav_about: "เกี่ยวกับเรา", nav_contact: "ติดต่อ", nav_admin: "แอดมิน",
    hero_kicker: "หัวหิน · ปราณบุรี · ชะอำ",
    hero_title_1: "ใช้ชีวิตริมทะเล", hero_title_2: "หรูหราอย่างเงียบสงบ",
    hero_sub: "คัดสรรพูลวิลล่า บ้านริมทะเล และที่ดินตลอดชายฝั่งเมืองหลวงเก่า สำหรับผู้ซื้อ ผู้เช่า และเจ้าของที่ต้องการมากกว่า",
    want_label: "ฉันต้องการ", buy: "ซื้อ", rent: "เช่า",
    location_label: "ทำเล", all_zones: "ทุกพื้นที่",
    type_label: "ประเภททรัพย์", any_type: "ทุกประเภท",
    budget_label: "งบประมาณ", any_price: "ทุกช่วงราคา",
    search_cta: "ค้นหาทรัพย์",
    cta_find: "ค้นหาบ้านของคุณ", cta_buy: "ซื้ออสังหาริมทรัพย์", cta_rent: "เช่าอสังหาริมทรัพย์", cta_list: "ฝากขาย/ฝากเช่า", cta_contact: "ติดต่อเอเจนต์",
    featured_title: "ทรัพย์แนะนำ", featured_sub: "คัดสรรพิเศษจากทั่วชายฝั่ง",
    view_details: "ดูรายละเอียด",
    areas_title: "สำรวจตามพื้นที่",
    area_hua_hin_desc: "เมืองชายทะเลหลวงดั้งเดิมของไทย พร้อมชายหาด สนามกอล์ฟ และสถานีรถไฟประวัติศาสตร์",
    area_pranburi_desc: "หาดทรายกว้างและที่ดินเงียบสงบ เหมาะสำหรับที่พักส่วนตัว",
    area_cha_am_desc: "เมืองชายทะเลบรรยากาศผ่อนคลาย ความต้องการเช่าสูง เดินทางจากกรุงเทพฯ สะดวก",
    about_title: "ทำไมต้อง huahin.properties",
    about_body: "เราคือเอเจนซี่บูทีคในหัวหิน ให้บริการเฉพาะพื้นที่หัวหิน ปราณบุรี และชะอำ ทุกรายการตรวจสอบด้วยตนเอง เจ้าของทุกรายผ่านการคัดกรอง และผู้ซื้อทุกคนได้รับการดูแลตั้งแต่ชมทรัพย์ครั้งแรกจนถึงวันโอนโฉนด",
    footer_rights: "สงวนลิขสิทธิ์",
    final_cta_title: "พร้อมค้นหาบ้านในฝันที่หัวหินหรือยัง?", footer_tagline: "เอเจนซี่อสังหาริมทรัพย์บูทีค เฉพาะพื้นที่หัวหิน ปราณบุรี และชะอำ", footer_explore: "สำรวจ", footer_company: "บริษัท", footer_contact: "ติดต่อ",
    share_site: "แชร์เว็บไซต์นี้", copy_link: "คัดลอกลิงก์", link_copied: "คัดลอกแล้ว!",
    login_signup: "เข้าสู่ระบบ / สมัครสมาชิก", bd_short: "ห้องนอน", ba_short: "ห้องน้ำ", properties_saved: "รายการที่บันทึกไว้", property_saved: "รายการที่บันทึกไว้",
    trust_local_title: "เชี่ยวชาญพื้นที่หัวหินโดยตรง", trust_local_desc: "เอเจนซี่บูทีคที่ทำงานในพื้นที่จริง หัวหิน ปราณบุรี และชะอำ",
    trust_verified_title: "ประกาศตรวจสอบแล้ว", trust_verified_desc: "ทุกทรัพย์ได้รับการตรวจสอบและยืนยันด้วยตนเองก่อนเผยแพร่",
    trust_lang_title: "บริการหลายภาษา", trust_lang_desc: "รองรับภาษาไทย อังกฤษ รัสเซีย จีน และอื่นๆ",
    trust_contact_title: "ติดต่อโดยตรง", trust_contact_desc: "ติดต่อเจ้าหน้าที่โดยตรงผ่าน LINE, WhatsApp หรือโทรศัพท์ — ไม่ผ่านคอลเซ็นเตอร์",
    listings_count: "รายการ",
    sort_label: "เรียงตาม", sort_newest: "ใหม่ล่าสุด", sort_price_asc: "ราคา: ต่ำไปสูง", sort_price_desc: "ราคา: สูงไปต่ำ",
    view_grid: "ตาราง", view_list: "รายการ",
    filters: "ตัวกรองรายละเอียดเพิ่มเติม", apply_filters: "ใช้ตัวกรอง", clear_filters: "ล้างค่า",
    keyword_label: "คำค้นหาหรือรหัสทรัพย์", keyword_placeholder: "เช่น HH-101 หรือ พูลวิลล่า",
    gallery_tab_photos: "รูปภาพ", gallery_tab_video: "วิดีโอนำชม", gallery_tab_360: "360° Tour", coming_soon: "เร็วๆ นี้",
    reviews_title: "รีวิวจากลูกค้า", no_reviews: "ยังไม่มีรีวิว", reviews_unit: "รีวิว", reviews_sample_note: "ข้อมูลตัวอย่าง",
    no_reviews_placeholder: "ยังไม่มีรีวิว — พื้นที่นี้เตรียมไว้สำหรับระบบรีวิวในเวอร์ชันถัดไป",
    mortgage_calc_title: "คำนวณสินเชื่อเบื้องต้น", mortgage_down_payment: "เงินดาวน์", mortgage_loan_years: "ระยะเวลากู้", years_unit: "ปี",
    mortgage_interest_rate: "อัตราดอกเบี้ย", mortgage_monthly_payment: "ผ่อนโดยประมาณ / เดือน",
    mortgage_disclaimer: "เป็นการประมาณเบื้องต้น (เงินต้น+ดอกเบี้ยเท่านั้น ไม่รวมค่าธรรมเนียม/ประกัน) ไม่ใช่ข้อเสนอสินเชื่อจริง",
    schedule_viewing_title: "นัดชมทรัพย์",
    bedrooms_label: "ห้องนอน", bathrooms_label: "ห้องน้ำ", land_size_label: "ขนาดที่ดิน", living_area_label: "พื้นที่ใช้สอย", any: "ทั้งหมด",
    status_label: "สถานะ", features_label: "คุณสมบัติ",
    no_results: "ไม่พบทรัพย์ที่ตรงกับตัวกรองของคุณ",
    sqm: "ตร.ม.", per_month: "/ เดือน",
    km_to: "กม. ถึง", mini_site_label: "มินิเว็บไซต์",
    beach: "ชายหาด", town: "ตัวเมือง",
    gallery_photo: "รูปภาพ",
    property_overview: "รายละเอียดสรุป", property_description: "รายละเอียดประกาศ", no_description: "ยังไม่มีรายละเอียด", property_features: "คุณสมบัติและสิ่งอำนวยความสะดวก", property_location: "ทำเล", property_general_area: "บริเวณโดยประมาณ", similar_properties: "ทรัพย์ใกล้เคียง",
    contact_agent: "ติดต่อเอเจนต์", enquiry_form: "ส่งข้อความสอบถาม", name_label: "ชื่อ", email_label: "อีเมล", phone_label: "เบอร์โทร", message_label: "ข้อความ", send: "ส่งข้อความ",
    call: "โทร", whatsapp: "WhatsApp", line_app: "Line", email_cta: "อีเมล",
    sell_title: "ฝากขาย / ฝากให้เช่าทรัพย์", sell_sub: "บอกรายละเอียดทรัพย์ของคุณ ทั้งขายหรือเช่า ทีมงานจะติดต่อกลับภายใน 24 ชั่วโมง",
    sell_owner_name: "ชื่อของคุณ", sell_owner_phone: "เบอร์โทร", sell_owner_email: "อีเมล", sell_owner_line: "Line ID (ถ้ามี)",
    sell_property_type: "ประเภททรัพย์", sell_listing_type: "ประเภทประกาศ", sell_area: "พื้นที่", sell_price: "ราคาที่ต้องการ", sell_notes: "รายละเอียดเพิ่มเติม",
    sell_submit: "ส่งข้อมูลทรัพย์",
    contact_title: "ติดต่อเรา", contact_sub: "มีคำถามเรื่องซื้อ เช่า หรือฝากขายในหัวหิน ปราณบุรี หรือชะอำ? เราพร้อมช่วยเหลือ",
    admin_login_title: "เข้าสู่ระบบแอดมิน", admin_username: "ชื่อผู้ใช้", admin_password: "รหัสผ่าน", admin_login_cta: "เข้าสู่ระบบ",
    admin_dashboard: "แดชบอร์ด", admin_listings: "รายการทรัพย์", admin_total: "รายการทั้งหมด", admin_for_sale: "ประกาศขาย", admin_for_rent: "ประกาศเช่า", admin_sold: "ขายแล้ว", admin_reserved: "จองแล้ว", admin_new: "รายการใหม่เดือนนี้",
    admin_add_property: "เพิ่มทรัพย์", admin_edit: "แก้ไข", admin_delete: "ลบ", admin_search: "ค้นหารายการ...",
    admin_owner_info: "ข้อมูลเจ้าของ (ส่วนตัว)", admin_internal_notes: "บันทึกภายใน", admin_photos: "รูปภาพ", admin_set_cover: "ตั้งเป็นรูปหลัก", admin_save: "บันทึกการเปลี่ยนแปลง", admin_saving: "กำลังบันทึก...", admin_save_success: "บันทึกสำเร็จ", admin_photos_note: "รูปภาพจะถูกบันทึกทันทีที่อัปโหลด ไม่ต้องรอกดปุ่มบันทึกการเปลี่ยนแปลง", admin_cancel: "ยกเลิก",
    admin_logout: "ออกจากระบบ", admin_signed_in_as: "เข้าสู่ระบบในฐานะแอดมิน",
    admin_field_title: "ชื่อทรัพย์", admin_field_zone: "โซน", admin_field_price: "ราคา (บาท)",
    admin_field_land_size: "ขนาดที่ดิน (ตร.ม.)", admin_field_living_area: "พื้นที่ใช้สอย (ตร.ม.)",
    admin_field_parking: "ที่จอดรถ", admin_field_ownership: "กรรมสิทธิ์",
    admin_field_distance_beach: "ระยะห่างชายหาด (กม.)", admin_field_distance_town: "ระยะห่างตัวเมือง (กม.)",
    admin_field_pool: "สระว่ายน้ำ", admin_field_furnished: "เฟอร์นิเจอร์",
    admin_furnished_full: "ครบชุด", admin_furnished_partial: "บางส่วน", admin_furnished_none: "ไม่มีเฟอร์นิเจอร์",
    admin_field_short_desc: "รายละเอียดโดยย่อ", admin_field_full_desc: "รายละเอียดเต็ม",
    admin_add_photo: "+ เพิ่มช่องรูปภาพ", admin_owner_disclaimer: "ไม่แสดงต่อสาธารณะ",
    admin_owner_name_ph: "ชื่อเจ้าของ", admin_owner_phone_ph: "เบอร์โทรเจ้าของ", admin_owner_email_ph: "อีเมลเจ้าของ", admin_owner_line_ph: "Line ID เจ้าของ",
    admin_owner_notes_ph: "บันทึกส่วนตัวเกี่ยวกับเจ้าของ",
    admin_owners_nav: "ผู้ติดต่อ", admin_owners_title: "ทำเนียบเจ้าของทรัพย์", admin_owners_sub: "เจ้าของทุกคนและทรัพย์ทุกรายการที่ฝากไว้กับเรา — ส่วนตัว เฉพาะแอดมิน",
    admin_owner_properties: "ทรัพย์ที่ฝาก", admin_view_on_map: "ดูแผนที่", admin_view_edit_property: "ดู/แก้ไขทรัพย์",
    admin_back_to_dashboard: "← กลับไปแดชบอร์ด", admin_new_owner: "+ เจ้าของใหม่", admin_owner_select: "เจ้าของ",
    admin_owner_photo1: "รูปเจ้าของ / บัตรประชาชน", admin_owner_photo2: "ภาพแคปหน้าจอการติดต่อ", admin_map_link: "ลิงก์แผนที่ (Google Maps URL)",
    admin_tenant_photo1: "รูปผู้เช่า / บัตรประชาชน", admin_tenant_photo2: "ภาพแคปหน้าจอการติดต่อ",
    admin_rented: "เช่าแล้ว", admin_lease_ends: "สัญญาหมดอายุ", admin_days_left: "วัน", admin_tenant: "ผู้เช่า",
    admin_showing_rented: "กำลังแสดงบ้านที่เช่าแล้ว เรียงจากใกล้หมดสัญญาที่สุด", admin_clear_view: "✕ ล้างตัวกรอง",
    status_rented: "เช่าแล้ว (มีผู้เช่าอยู่)", admin_lease_start: "วันที่เริ่มเช่า", admin_lease_end: "วันที่สิ้นสุดสัญญา",
    admin_tenant_info: "ข้อมูลผู้เช่า", admin_tenant_select: "ผู้เช่า", admin_new_tenant: "+ ผู้เช่าใหม่",
    admin_tenant_name_ph: "ชื่อผู้เช่า", admin_tenant_phone_ph: "เบอร์โทรผู้เช่า", admin_tenant_email_ph: "อีเมลผู้เช่า", admin_tenant_line_ph: "Line ID ผู้เช่า", admin_tenant_notes_ph: "บันทึกเกี่ยวกับผู้เช่า",
    contacts_title: "ทำเนียบผู้ติดต่อ", contacts_sub: "เจ้าของ ผู้เช่า และทรัพย์ทุกรายการที่เชื่อมโยงกัน — ส่วนตัว เฉพาะแอดมิน",
    contacts_tab_owners: "เจ้าของทรัพย์", contacts_tab_tenants: "ผู้เช่า", admin_lease_ends_col: "สัญญาหมดอายุ",
    admin_map_title: "แผนที่ทรัพย์สิน", admin_map_sub: "เลื่อนดูแผนที่จริงของหัวหิน ปราณบุรี และชะอำ จากนั้นคลิกที่รายการด้านล่างเพื่อดูบนแผนที่หรือเปิดแก้ไข", admin_map_note: "แผนที่ Google Maps จริงด้านบน (ยังไม่ได้ตั้งค่า API key สำหรับปักหมุดกำหนดเองในตัวอย่างนี้) — ใช้รายการด้านล่างที่แยกสีตามประเภทด้านล่างเพื่อเรียกดูและคลิกเข้าดูรายการได้", admin_map_nav: "แผนที่",
  },
  ru: {
    site_name: "huahin.properties",
    nav_buy: "Купить", nav_rent: "Снять", nav_sell: "Продать / Сдать", nav_about: "О нас", nav_contact: "Контакты", nav_admin: "Админ",
    hero_kicker: "Хуахин · Пранбури · Ча-Ам",
    hero_title_1: "Жизнь у моря,", hero_title_2: "тихая роскошь.",
    hero_sub: "Избранные виллы с бассейном, дома у моря и земля вдоль королевского побережья Таиланда — для взыскательных покупателей, арендаторов и владельцев.",
    want_label: "Я хочу", buy: "Купить", rent: "Снять",
    location_label: "Локация", all_zones: "Все районы",
    type_label: "Тип недвижимости", any_type: "Любой тип",
    budget_label: "Бюджет", any_price: "Любая цена",
    search_cta: "Найти недвижимость",
    cta_find: "Найти дом", cta_buy: "Купить недвижимость", cta_rent: "Снять недвижимость", cta_list: "Разместить объект", cta_contact: "Связаться с агентом",
    featured_title: "Избранные объекты", featured_sub: "Подборка лучших предложений побережья",
    view_details: "Подробнее",
    areas_title: "Выбрать по району",
    area_hua_hin_desc: "Первый королевский приморский город Таиланда — пляжи, гольф и историческая железная дорога.",
    area_pranburi_desc: "Широкие песчаные пляжи и тихая земля — предпочтение для частных резиденций.",
    area_cha_am_desc: "Спокойный приморский город с высоким спросом на аренду и удобной связью с Бангкоком.",
    about_title: "Почему huahin.properties",
    about_body: "Мы бутик-агентство в Хуахине, работающее исключительно в Хуахине, Пранбури и Ча-Ам. Каждый объект проверяется лично, каждый владелец — с проверкой, а каждый покупатель сопровождается от первого просмотра до подписания документа Chanote.",
    footer_rights: "Все права защищены.",
    final_cta_title: "Готовы найти дом своей мечты в Хуахине?", footer_tagline: "Бутик-агентство недвижимости в Хуахине, Пранбури и Ча-Аме.", footer_explore: "Навигация", footer_company: "Компания", footer_contact: "Контакты",
    share_site: "Поделиться сайтом", copy_link: "Скопировать ссылку", link_copied: "Ссылка скопирована!",
    login_signup: "Войти / Регистрация", bd_short: "спальни", ba_short: "ванные", properties_saved: "объектов сохранено", property_saved: "объект сохранён",
    trust_local_title: "Локальная экспертиза в Хуахине", trust_local_desc: "Бутик-агентство, работающее на месте в Хуахине, Пранбури и Ча-Аме.",
    trust_verified_title: "Проверенные объявления", trust_verified_desc: "Каждый объект осматривается и проверяется лично перед публикацией.",
    trust_lang_title: "Многоязычный сервис", trust_lang_desc: "Поддержка на тайском, английском, русском, китайском и других языках.",
    trust_contact_title: "Прямой контакт", trust_contact_desc: "Связь напрямую с агентом через LINE, WhatsApp или телефон — без колл-центров.",
    listings_count: "объектов",
    sort_label: "Сортировка", sort_newest: "Сначала новые", sort_price_asc: "Цена: по возрастанию", sort_price_desc: "Цена: по убыванию",
    view_grid: "Сетка", view_list: "Список",
    filters: "Фильтры", apply_filters: "Применить фильтры", clear_filters: "Сбросить",
    keyword_label: "Ключевое слово или код объекта", keyword_placeholder: "напр. HH-101 или вилла с бассейном",
    gallery_tab_photos: "Фото", gallery_tab_video: "Видеотур", gallery_tab_360: "Тур 360°", coming_soon: "скоро",
    reviews_title: "Отзывы клиентов", no_reviews: "Пока нет отзывов", reviews_unit: "отзывов", reviews_sample_note: "образец данных",
    no_reviews_placeholder: "Пока нет отзывов — этот раздел появится в будущей версии.",
    mortgage_calc_title: "Расчёт ипотеки", mortgage_down_payment: "Первый взнос", mortgage_loan_years: "Срок кредита", years_unit: "лет",
    mortgage_interest_rate: "Процентная ставка", mortgage_monthly_payment: "Примерный платёж/мес.",
    mortgage_disclaimer: "Это базовая оценка (только основной долг + проценты, без сборов/страховки) — не является реальным предложением кредита.",
    schedule_viewing_title: "Записаться на просмотр",
    bedrooms_label: "Спальни", bathrooms_label: "Ванные", land_size_label: "Площадь участка", living_area_label: "Жилая площадь", any: "Любое",
    status_label: "Статус", features_label: "Особенности",
    no_results: "Нет объектов, соответствующих фильтрам.",
    sqm: "кв.м", per_month: "/ месяц",
    km_to: "км до", mini_site_label: "Мини-сайт",
    beach: "пляж", town: "город",
    gallery_photo: "Фото",
    property_overview: "Обзор", property_description: "Описание", no_description: "Описание пока не добавлено.", property_features: "Особенности и удобства", property_location: "Расположение", property_general_area: "Примерный район", similar_properties: "Похожие объекты",
    contact_agent: "Связаться с агентом", enquiry_form: "Отправить запрос", name_label: "Имя", email_label: "Email", phone_label: "Телефон", message_label: "Сообщение", send: "Отправить запрос",
    call: "Позвонить", whatsapp: "WhatsApp", line_app: "Line", email_cta: "Email",
    sell_title: "Разместить объект", sell_sub: "Расскажите нам о вашей недвижимости — на продажу или в аренду — и наша команда свяжется с вами в течение 24 часов.",
    sell_owner_name: "Ваше имя", sell_owner_phone: "Телефон", sell_owner_email: "Email", sell_owner_line: "Line ID (необязательно)",
    sell_property_type: "Тип недвижимости", sell_listing_type: "Тип объявления", sell_area: "Район", sell_price: "Желаемая цена", sell_notes: "Дополнительная информация",
    sell_submit: "Отправить объект",
    contact_title: "Связаться с нами", contact_sub: "Вопросы о покупке, аренде или размещении в Хуахине, Пранбури или Ча-Ам? Мы на связи.",
    admin_login_title: "Вход для админа", admin_username: "Логин", admin_password: "Пароль", admin_login_cta: "Войти",
    admin_dashboard: "Панель управления", admin_listings: "Объекты", admin_total: "Всего объектов", admin_for_sale: "На продажу", admin_for_rent: "В аренду", admin_sold: "Продано", admin_reserved: "Забронировано", admin_new: "Новых за месяц",
    admin_add_property: "Добавить объект", admin_edit: "Изменить", admin_delete: "Удалить", admin_search: "Поиск объектов...",
    admin_owner_info: "Данные владельца (приватно)", admin_internal_notes: "Внутренние заметки", admin_photos: "Фото", admin_set_cover: "Сделать обложкой", admin_save: "Сохранить изменения", admin_saving: "Сохранение...", admin_save_success: "Успешно сохранено", admin_photos_note: "Фото сохраняются сразу при загрузке — не нужно ждать кнопку сохранения.", admin_cancel: "Отмена",
    admin_logout: "Выйти", admin_signed_in_as: "Вход выполнен как админ",
    admin_field_title: "Название", admin_field_zone: "Район", admin_field_price: "Цена (THB)",
    admin_field_land_size: "Площадь участка (кв.м)", admin_field_living_area: "Жилая площадь (кв.м)",
    admin_field_parking: "Парковка", admin_field_ownership: "Право собственности",
    admin_field_distance_beach: "Расстояние до пляжа (км)", admin_field_distance_town: "Расстояние до города (км)",
    admin_field_pool: "Бассейн", admin_field_furnished: "Меблировка",
    admin_furnished_full: "Полностью меблировано", admin_furnished_partial: "Частично меблировано", admin_furnished_none: "Без мебели",
    admin_field_short_desc: "Краткое описание", admin_field_full_desc: "Полное описание",
    admin_add_photo: "+ Добавить фото", admin_owner_disclaimer: "никогда не показывается публично",
    admin_owner_name_ph: "Имя владельца", admin_owner_phone_ph: "Телефон владельца", admin_owner_email_ph: "Email владельца", admin_owner_line_ph: "Line ID владельца",
    admin_owner_notes_ph: "Приватные заметки о владельце",
    admin_owners_nav: "Контакты", admin_owners_title: "Справочник владельцев", admin_owners_sub: "Все владельцы и все объекты, которые они разместили у нас — приватно, только для админа.",
    admin_owner_properties: "Объекты", admin_view_on_map: "Смотреть на карте", admin_view_edit_property: "Смотреть / редактировать объект",
    admin_back_to_dashboard: "← Назад к панели", admin_new_owner: "+ Новый владелец", admin_owner_select: "Владелец",
    admin_owner_photo1: "Фото владельца / ID", admin_owner_photo2: "Скриншот переписки", admin_map_link: "Ссылка на карту (Google Maps URL)",
    admin_tenant_photo1: "Фото арендатора / ID", admin_tenant_photo2: "Скриншот переписки",
    admin_rented: "Сдано в аренду", admin_lease_ends: "Окончание аренды", admin_days_left: "дней осталось", admin_tenant: "Арендатор",
    admin_showing_rented: "Показаны сданные объекты, ближайшее окончание аренды сначала", admin_clear_view: "✕ Сбросить",
    status_rented: "Сдано (занято)", admin_lease_start: "Начало аренды", admin_lease_end: "Окончание аренды",
    admin_tenant_info: "Данные арендатора", admin_tenant_select: "Арендатор", admin_new_tenant: "+ Новый арендатор",
    admin_tenant_name_ph: "Имя арендатора", admin_tenant_phone_ph: "Телефон арендатора", admin_tenant_email_ph: "Email арендатора", admin_tenant_line_ph: "Line ID арендатора", admin_tenant_notes_ph: "Заметки об арендаторе",
    contacts_title: "Справочник контактов", contacts_sub: "Владельцы, арендаторы и все связанные с ними объекты — приватно, только для админа.",
    contacts_tab_owners: "Владельцы", contacts_tab_tenants: "Арендаторы", admin_lease_ends_col: "Окончание аренды",
    admin_map_title: "Карта объектов", admin_map_sub: "Просмотрите живую карту Хуахина, Пранбури и Ча-Ам, затем нажмите любой объект ниже, чтобы посмотреть его на карте или открыть для редактирования.", admin_map_note: "Выше встроена настоящая карта Google (API-ключ для пользовательских меток в этом прототипе не настроен) — используйте список с цветовыми метками ниже, чтобы просматривать по типу и переходить к объектам.", admin_map_nav: "Карта",
  },
  no: {
    site_name: "huahin.properties",
    nav_buy: "Kjøp", nav_rent: "Leie", nav_sell: "Selg / Legg ut", nav_about: "Om oss", nav_contact: "Kontakt", nav_admin: "Admin",
    hero_kicker: "Hua Hin · Pranburi · Cha-am",
    hero_title_1: "Liv ved kysten,", hero_title_2: "stillferdig luksuriøst.",
    hero_sub: "Utvalgte bassengvillaer, strandhus og tomter langs Thailands kongelige kyst — for kjøpere, leietakere og eiere som forventer mer.",
    want_label: "Jeg vil", buy: "Kjøpe", rent: "Leie",
    location_label: "Beliggenhet", all_zones: "Alle områder",
    type_label: "Eiendomstype", any_type: "Alle typer",
    budget_label: "Budsjett", any_price: "Alle priser",
    search_cta: "Søk etter eiendom",
    cta_find: "Finn ditt hjem", cta_buy: "Kjøp eiendom", cta_rent: "Lei eiendom", cta_list: "Legg ut eiendom", cta_contact: "Kontakt megler",
    featured_title: "Utvalgte eiendommer", featured_sub: "Et håndplukket utvalg langs kysten",
    view_details: "Se detaljer",
    areas_title: "Utforsk etter område",
    area_hua_hin_desc: "Thailands opprinnelige kongelige kystby — strender, golf og den historiske jernbanen.",
    area_pranburi_desc: "Brede sandstrender og rolige tomter, populært for private tilfluktssteder.",
    area_cha_am_desc: "En avslappet strandby med høy etterspørsel etter utleie og enkel tilgang til Bangkok.",
    about_title: "Hvorfor huahin.properties",
    about_body: "Vi er et boutique-byrå basert i Hua Hin, som utelukkende jobber i Hua Hin, Pranburi og Cha-am. Hver eiendom er verifisert personlig, hver eier er sjekket, og hver kjøper blir fulgt opp fra første visning til signert Chanote-skjøte.",
    footer_rights: "Alle rettigheter reservert.",
    final_cta_title: "Klar til å finne hjemmet ditt i Hua Hin?", footer_tagline: "Et boutique-eiendomsmeglerfirma for Hua Hin, Pranburi og Cha-am.", footer_explore: "Utforsk", footer_company: "Selskap", footer_contact: "Kontakt",
    share_site: "Del denne siden", copy_link: "Kopier lenke", link_copied: "Lenke kopiert!",
    login_signup: "Logg inn / Registrer deg", bd_short: "sov", ba_short: "bad", properties_saved: "eiendommer lagret", property_saved: "eiendom lagret",
    trust_local_title: "Lokal ekspertise i Hua Hin", trust_local_desc: "Boutique-byrå med lokal tilstedeværelse i Hua Hin, Pranburi og Cha-am.",
    trust_verified_title: "Verifiserte annonser", trust_verified_desc: "Hver eiendom blir inspisert og verifisert personlig før publisering.",
    trust_lang_title: "Flerspråklig service", trust_lang_desc: "Støtte på thai, engelsk, russisk, kinesisk og mer.",
    trust_contact_title: "Direkte kontakt", trust_contact_desc: "Nå en megler direkte via LINE, WhatsApp eller telefon — ingen kundesenter.",
    listings_count: "annonser",
    sort_label: "Sorter", sort_newest: "Nyeste", sort_price_asc: "Pris: lav til høy", sort_price_desc: "Pris: høy til lav",
    view_grid: "Rutenett", view_list: "Liste",
    filters: "Filtre", apply_filters: "Bruk filtre", clear_filters: "Tøm",
    keyword_label: "Søkeord eller eiendomskode", keyword_placeholder: "f.eks. HH-101 eller bassengvilla",
    gallery_tab_photos: "Bilder", gallery_tab_video: "Videovisning", gallery_tab_360: "360°-tur", coming_soon: "kommer snart",
    reviews_title: "Kundeanmeldelser", no_reviews: "Ingen anmeldelser ennå", reviews_unit: "anmeldelser", reviews_sample_note: "eksempeldata",
    no_reviews_placeholder: "Ingen anmeldelser ennå — denne plassen er reservert for anmeldelsessystemet i en fremtidig versjon.",
    mortgage_calc_title: "Boliglånskalkulator", mortgage_down_payment: "Egenkapital", mortgage_loan_years: "Lånetid", years_unit: "år",
    mortgage_interest_rate: "Rente", mortgage_monthly_payment: "Est. månedlig avdrag",
    mortgage_disclaimer: "Dette er et grunnleggende estimat (kun hovedstol + rente, uten gebyrer/forsikring) — ikke et reelt lånetilbud.",
    schedule_viewing_title: "Book visning",
    bedrooms_label: "Soverom", bathrooms_label: "Bad", land_size_label: "Tomtestørrelse", living_area_label: "Boareal", any: "Alle",
    status_label: "Status", features_label: "Fasiliteter",
    no_results: "Ingen eiendommer samsvarer med filtrene dine.",
    sqm: "kvm", per_month: "/ måned",
    km_to: "km til", mini_site_label: "Miniside",
    beach: "strand", town: "by",
    gallery_photo: "Bilde",
    property_overview: "Oversikt", property_description: "Beskrivelse", no_description: "Ingen beskrivelse ennå.", property_features: "Fasiliteter", property_location: "Beliggenhet", property_general_area: "Omtrentlig område", similar_properties: "Lignende eiendommer",
    contact_agent: "Kontakt megler", enquiry_form: "Send en forespørsel", name_label: "Navn", email_label: "E-post", phone_label: "Telefon", message_label: "Melding", send: "Send forespørsel",
    call: "Ring", whatsapp: "WhatsApp", line_app: "Line", email_cta: "E-post",
    sell_title: "Legg ut din eiendom", sell_sub: "Fortell oss om eiendommen din — til salgs eller utleie — så tar teamet vårt kontakt innen 24 timer.",
    sell_owner_name: "Ditt navn", sell_owner_phone: "Telefon", sell_owner_email: "E-post", sell_owner_line: "Line-ID (valgfritt)",
    sell_property_type: "Eiendomstype", sell_listing_type: "Annonsetype", sell_area: "Område", sell_price: "Ønsket pris", sell_notes: "Fortell oss mer",
    sell_submit: "Send inn eiendom",
    contact_title: "Kontakt oss", contact_sub: "Spørsmål om kjøp, leie eller annonsering i Hua Hin, Pranburi eller Cha-am? Vi er her for deg.",
    admin_login_title: "Admin-innlogging", admin_username: "Brukernavn", admin_password: "Passord", admin_login_cta: "Logg inn",
    admin_dashboard: "Dashbord", admin_listings: "Annonser", admin_total: "Totalt antall annonser", admin_for_sale: "Til salgs", admin_for_rent: "Til leie", admin_sold: "Solgt", admin_reserved: "Reservert", admin_new: "Nye denne måneden",
    admin_add_property: "Legg til eiendom", admin_edit: "Rediger", admin_delete: "Slett", admin_search: "Søk i annonser...",
    admin_owner_info: "Eierinformasjon (privat)", admin_internal_notes: "Interne notater", admin_photos: "Bilder", admin_set_cover: "Sett som forsidebilde", admin_save: "Lagre endringer", admin_saving: "Lagrer…", admin_save_success: "Lagret", admin_photos_note: "Bilder lagres umiddelbart ved opplasting — ingen grunn til å vente på Lagre endringer.", admin_cancel: "Avbryt",
    admin_logout: "Logg ut", admin_signed_in_as: "Logget inn som Admin",
    admin_field_title: "Tittel", admin_field_zone: "Sone", admin_field_price: "Pris (THB)",
    admin_field_land_size: "Tomtestørrelse (kvm)", admin_field_living_area: "Boareal (kvm)",
    admin_field_parking: "Parkering", admin_field_ownership: "Eierform",
    admin_field_distance_beach: "Avstand til stranden (km)", admin_field_distance_town: "Avstand til byen (km)",
    admin_field_pool: "Svømmebasseng", admin_field_furnished: "Møblert",
    admin_furnished_full: "Fullt møblert", admin_furnished_partial: "Delvis møblert", admin_furnished_none: "Umøblert",
    admin_field_short_desc: "Kort beskrivelse", admin_field_full_desc: "Full beskrivelse",
    admin_add_photo: "+ Legg til bildeplass", admin_owner_disclaimer: "vises aldri offentlig",
    admin_owner_name_ph: "Eierens navn", admin_owner_phone_ph: "Eierens telefon", admin_owner_email_ph: "Eierens e-post", admin_owner_line_ph: "Eierens Line-ID",
    admin_owner_notes_ph: "Private notater om eieren",
    admin_owners_nav: "Kontakter", admin_owners_title: "Eierregister", admin_owners_sub: "Hver eier og hver eiendom de har lagt ut hos oss — privat, kun for admin.",
    admin_owner_properties: "Eiendommer", admin_view_on_map: "Vis på kart", admin_view_edit_property: "Vis / rediger eiendom",
    admin_back_to_dashboard: "← Tilbake til dashbordet", admin_new_owner: "+ Ny eier", admin_owner_select: "Eier",
    admin_owner_photo1: "Eierens bilde / ID", admin_owner_photo2: "Skjermbilde av kontakt", admin_map_link: "Kartlenke (Google Maps-URL)",
    admin_tenant_photo1: "Leietakerens bilde / ID", admin_tenant_photo2: "Skjermbilde av kontakt",
    admin_rented: "Utleid nå", admin_lease_ends: "Leieavtale slutter", admin_days_left: "dager igjen", admin_tenant: "Leietaker",
    admin_showing_rented: "Viser utleide eiendommer, nærmeste leieslutt først", admin_clear_view: "✕ Tøm",
    status_rented: "Utleid (opptatt)", admin_lease_start: "Leiestart", admin_lease_end: "Leieslutt",
    admin_tenant_info: "Leietakerinformasjon", admin_tenant_select: "Leietaker", admin_new_tenant: "+ Ny leietaker",
    admin_tenant_name_ph: "Leietakerens navn", admin_tenant_phone_ph: "Leietakerens telefon", admin_tenant_email_ph: "Leietakerens e-post", admin_tenant_line_ph: "Leietakerens Line-ID", admin_tenant_notes_ph: "Notater om leietakeren",
    contacts_title: "Kontaktregister", contacts_sub: "Eiere, leietakere og alle eiendommer knyttet til dem — privat, kun for admin.",
    contacts_tab_owners: "Eiere", contacts_tab_tenants: "Leietakere", admin_lease_ends_col: "Leieslutt",
    admin_map_title: "Eiendomskart", admin_map_sub: "Bla gjennom det direkte kartet over Hua Hin, Pranburi og Cha-am, og klikk deretter på en annonse nedenfor for å se den på kartet eller åpne den for redigering.", admin_map_note: "Ekte Google Maps-innbygging over (ingen API-nøkkel konfigurert for egendefinerte pinner i denne prototypen) — bruk den fargekodede listen nedenfor for å bla etter type og gå til annonser.", admin_map_nav: "Kart",
  },
  de: {
    site_name: "huahin.properties",
    nav_buy: "Kaufen", nav_rent: "Mieten", nav_sell: "Verkaufen / Inserieren", nav_about: "Über uns", nav_contact: "Kontakt", nav_admin: "Admin",
    hero_kicker: "Hua Hin · Pranburi · Cha-am",
    hero_title_1: "Leben an der Küste,", hero_title_2: "leise luxuriös.",
    hero_sub: "Ausgewählte Poolvillen, Strandhäuser und Grundstücke entlang Thailands königlicher Küste — für Käufer, Mieter und Eigentümer, die mehr erwarten.",
    want_label: "Ich möchte", buy: "Kaufen", rent: "Mieten",
    location_label: "Standort", all_zones: "Alle Gebiete",
    type_label: "Immobilientyp", any_type: "Alle Typen",
    budget_label: "Budget", any_price: "Jeder Preis",
    search_cta: "Immobilien suchen",
    cta_find: "Finden Sie Ihr Zuhause", cta_buy: "Immobilie kaufen", cta_rent: "Immobilie mieten", cta_list: "Immobilie inserieren", cta_contact: "Makler kontaktieren",
    featured_title: "Ausgewählte Immobilien", featured_sub: "Eine handverlesene Auswahl entlang der Küste",
    view_details: "Details ansehen",
    areas_title: "Nach Gebiet erkunden",
    area_hua_hin_desc: "Thailands ursprüngliche königliche Küstenstadt — Strände, Golf und die historische Eisenbahn.",
    area_pranburi_desc: "Weite Sandstrände und ruhiges Land, beliebt für private Rückzugsorte.",
    area_cha_am_desc: "Eine entspannte Strandstadt mit hoher Mietnachfrage und einfacher Anbindung nach Bangkok.",
    about_title: "Warum huahin.properties",
    about_body: "Wir sind eine Boutique-Agentur mit Sitz in Hua Hin, die ausschließlich in Hua Hin, Pranburi und Cha-am tätig ist. Jedes Angebot wird persönlich geprüft, jeder Eigentümer überprüft, und jeder Käufer wird von der ersten Besichtigung bis zur Unterzeichnung des Chanote begleitet.",
    footer_rights: "Alle Rechte vorbehalten.",
    final_cta_title: "Bereit, Ihr Zuhause in Hua Hin zu finden?", footer_tagline: "Eine Boutique-Immobilienagentur für Hua Hin, Pranburi und Cha-am.", footer_explore: "Entdecken", footer_company: "Unternehmen", footer_contact: "Kontakt",
    share_site: "Seite teilen", copy_link: "Link kopieren", link_copied: "Link kopiert!",
    login_signup: "Anmelden / Registrieren", bd_short: "Schlafz.", ba_short: "Badez.", properties_saved: "Objekte gespeichert", property_saved: "Objekt gespeichert",
    trust_local_title: "Lokale Expertise in Hua Hin", trust_local_desc: "Boutique-Agentur mit Präsenz vor Ort in Hua Hin, Pranburi und Cha-am.",
    trust_verified_title: "Verifizierte Angebote", trust_verified_desc: "Jede Immobilie wird vor Veröffentlichung persönlich besichtigt und geprüft.",
    trust_lang_title: "Mehrsprachiger Service", trust_lang_desc: "Unterstützung in Thai, Englisch, Russisch, Chinesisch und mehr.",
    trust_contact_title: "Direkter Kontakt", trust_contact_desc: "Direkter Kontakt zu einem Makler über LINE, WhatsApp oder Telefon — keine Callcenter.",
    listings_count: "Angebote",
    sort_label: "Sortieren", sort_newest: "Neueste", sort_price_asc: "Preis: aufsteigend", sort_price_desc: "Preis: absteigend",
    view_grid: "Raster", view_list: "Liste",
    filters: "Filter", apply_filters: "Filter anwenden", clear_filters: "Zurücksetzen",
    keyword_label: "Suchbegriff oder Objektcode", keyword_placeholder: "z.B. HH-101 oder Pool-Villa",
    gallery_tab_photos: "Fotos", gallery_tab_video: "Video-Rundgang", gallery_tab_360: "360°-Tour", coming_soon: "demnächst",
    reviews_title: "Kundenbewertungen", no_reviews: "Noch keine Bewertungen", reviews_unit: "Bewertungen", reviews_sample_note: "Beispieldaten",
    no_reviews_placeholder: "Noch keine Bewertungen — dieser Bereich ist für das Bewertungssystem einer zukünftigen Version reserviert.",
    mortgage_calc_title: "Hypothekenrechner", mortgage_down_payment: "Anzahlung", mortgage_loan_years: "Laufzeit", years_unit: "Jahre",
    mortgage_interest_rate: "Zinssatz", mortgage_monthly_payment: "Geschätzte Monatsrate",
    mortgage_disclaimer: "Dies ist eine grobe Schätzung (nur Zins + Tilgung, ohne Gebühren/Versicherung) — kein echtes Kreditangebot.",
    schedule_viewing_title: "Besichtigung vereinbaren",
    bedrooms_label: "Schlafzimmer", bathrooms_label: "Badezimmer", land_size_label: "Grundstücksgröße", living_area_label: "Wohnfläche", any: "Beliebig",
    status_label: "Status", features_label: "Ausstattung",
    no_results: "Keine Immobilien entsprechen Ihren Filtern.",
    sqm: "m²", per_month: "/ Monat",
    km_to: "km bis", mini_site_label: "Mini-Website",
    beach: "Strand", town: "Stadt",
    gallery_photo: "Foto",
    property_overview: "Übersicht", property_description: "Beschreibung", no_description: "Noch keine Beschreibung vorhanden.", property_features: "Ausstattung & Annehmlichkeiten", property_location: "Lage", property_general_area: "Ungefähre Lage", similar_properties: "Ähnliche Immobilien",
    contact_agent: "Makler kontaktieren", enquiry_form: "Anfrage senden", name_label: "Name", email_label: "E-Mail", phone_label: "Telefon", message_label: "Nachricht", send: "Anfrage senden",
    call: "Anrufen", whatsapp: "WhatsApp", line_app: "Line", email_cta: "E-Mail",
    sell_title: "Immobilie inserieren", sell_sub: "Erzählen Sie uns von Ihrer Immobilie — zum Verkauf oder zur Miete — und unser Team meldet sich innerhalb von 24 Stunden.",
    sell_owner_name: "Ihr Name", sell_owner_phone: "Telefon", sell_owner_email: "E-Mail", sell_owner_line: "Line-ID (optional)",
    sell_property_type: "Immobilientyp", sell_listing_type: "Angebotstyp", sell_area: "Gebiet", sell_price: "Preisvorstellung", sell_notes: "Mehr erzählen",
    sell_submit: "Immobilie einreichen",
    contact_title: "Kontaktieren Sie uns", contact_sub: "Fragen zum Kauf, zur Miete oder zum Inserieren in Hua Hin, Pranburi oder Cha-am? Wir sind für Sie da.",
    admin_login_title: "Admin-Anmeldung", admin_username: "Benutzername", admin_password: "Passwort", admin_login_cta: "Anmelden",
    admin_dashboard: "Dashboard", admin_listings: "Angebote", admin_total: "Angebote gesamt", admin_for_sale: "Zu verkaufen", admin_for_rent: "Zu vermieten", admin_sold: "Verkauft", admin_reserved: "Reserviert", admin_new: "Neu diesen Monat",
    admin_add_property: "Immobilie hinzufügen", admin_edit: "Bearbeiten", admin_delete: "Löschen", admin_search: "Angebote suchen...",
    admin_owner_info: "Eigentümerdaten (privat)", admin_internal_notes: "Interne Notizen", admin_photos: "Fotos", admin_set_cover: "Als Titelbild festlegen", admin_save: "Änderungen speichern", admin_saving: "Wird gespeichert…", admin_save_success: "Erfolgreich gespeichert", admin_photos_note: "Fotos werden sofort beim Hochladen gespeichert — kein Warten auf Speichern nötig.", admin_cancel: "Abbrechen",
    admin_logout: "Abmelden", admin_signed_in_as: "Angemeldet als Admin",
    admin_field_title: "Titel", admin_field_zone: "Zone", admin_field_price: "Preis (THB)",
    admin_field_land_size: "Grundstücksgröße (m²)", admin_field_living_area: "Wohnfläche (m²)",
    admin_field_parking: "Parkplätze", admin_field_ownership: "Eigentumsverhältnis",
    admin_field_distance_beach: "Entfernung zum Strand (km)", admin_field_distance_town: "Entfernung zur Stadt (km)",
    admin_field_pool: "Schwimmbad", admin_field_furnished: "Möbliert",
    admin_furnished_full: "Voll möbliert", admin_furnished_partial: "Teilmöbliert", admin_furnished_none: "Unmöbliert",
    admin_field_short_desc: "Kurzbeschreibung", admin_field_full_desc: "Vollständige Beschreibung",
    admin_add_photo: "+ Fotoplatz hinzufügen", admin_owner_disclaimer: "niemals öffentlich angezeigt",
    admin_owner_name_ph: "Name des Eigentümers", admin_owner_phone_ph: "Telefon des Eigentümers", admin_owner_email_ph: "E-Mail des Eigentümers", admin_owner_line_ph: "Line-ID des Eigentümers",
    admin_owner_notes_ph: "Private Notizen zum Eigentümer",
    admin_owners_nav: "Kontakte", admin_owners_title: "Eigentümerverzeichnis", admin_owners_sub: "Jeder Eigentümer und jede bei uns gelistete Immobilie — privat, nur für Admin.",
    admin_owner_properties: "Immobilien", admin_view_on_map: "Auf Karte ansehen", admin_view_edit_property: "Immobilie ansehen / bearbeiten",
    admin_back_to_dashboard: "← Zurück zum Dashboard", admin_new_owner: "+ Neuer Eigentümer", admin_owner_select: "Eigentümer",
    admin_owner_photo1: "Foto / Ausweis des Eigentümers", admin_owner_photo2: "Kontakt-Screenshot", admin_map_link: "Kartenlink (Google Maps URL)",
    admin_tenant_photo1: "Foto / Ausweis des Mieters", admin_tenant_photo2: "Kontakt-Screenshot",
    admin_rented: "Aktuell vermietet", admin_lease_ends: "Mietende", admin_days_left: "Tage verbleibend", admin_tenant: "Mieter",
    admin_showing_rented: "Vermietete Immobilien werden angezeigt, frühestes Mietende zuerst", admin_clear_view: "✕ Zurücksetzen",
    status_rented: "Vermietet (belegt)", admin_lease_start: "Mietbeginn", admin_lease_end: "Mietende",
    admin_tenant_info: "Mieterdaten", admin_tenant_select: "Mieter", admin_new_tenant: "+ Neuer Mieter",
    admin_tenant_name_ph: "Name des Mieters", admin_tenant_phone_ph: "Telefon des Mieters", admin_tenant_email_ph: "E-Mail des Mieters", admin_tenant_line_ph: "Line-ID des Mieters", admin_tenant_notes_ph: "Notizen zum Mieter",
    contacts_title: "Kontaktverzeichnis", contacts_sub: "Eigentümer, Mieter und alle damit verbundenen Immobilien — privat, nur für Admin.",
    contacts_tab_owners: "Eigentümer", contacts_tab_tenants: "Mieter", admin_lease_ends_col: "Mietende",
    admin_map_title: "Immobilienkarte", admin_map_sub: "Durchsuchen Sie die Live-Karte von Hua Hin, Pranburi und Cha-am und klicken Sie dann auf ein Angebot unten, um es auf der Karte anzuzeigen oder zu bearbeiten.", admin_map_note: "Echte Google-Maps-Einbettung oben (kein API-Schlüssel für benutzerdefinierte Pins in diesem Prototyp konfiguriert) — nutzen Sie die farblich codierte Liste unten, um nach Typ zu durchsuchen und zu Angeboten zu gelangen.", admin_map_nav: "Karte",
  },
  zh: {
    site_name: "huahin.properties",
    nav_buy: "购买", nav_rent: "租赁", nav_sell: "委托出售/出租", nav_about: "关于我们", nav_contact: "联系我们", nav_admin: "管理后台",
    hero_kicker: "华欣 · 巴蓝武里 · 差安",
    hero_title_1: "海岸生活，", hero_title_2: "低调奢华。",
    hero_sub: "精选泰国皇家海岸沿线的泳池别墅、海滨住宅与土地——献给追求更多的买家、租客与业主。",
    want_label: "我想要", buy: "购买", rent: "租赁",
    location_label: "地区", all_zones: "所有地区",
    type_label: "房产类型", any_type: "任意类型",
    budget_label: "预算", any_price: "不限价格",
    search_cta: "搜索房源",
    cta_find: "寻找您的家", cta_buy: "购买房产", cta_rent: "租赁房产", cta_list: "委托出售/出租", cta_contact: "联系经纪人",
    featured_title: "精选房源", featured_sub: "沿海岸精心挑选",
    view_details: "查看详情",
    areas_title: "按地区探索",
    area_hua_hin_desc: "泰国原始的皇家海滨小镇——沙滩、高尔夫与历史悠久的火车站。",
    area_pranburi_desc: "宽阔的沙滩与宁静的土地，深受私人度假住宅青睐。",
    area_cha_am_desc: "悠闲的海滨小镇，租赁需求旺盛，往返曼谷交通便利。",
    about_title: "为什么选择 huahin.properties",
    about_body: "我们是总部位于华欣的精品地产公司，专注于华欣、巴蓝武里与差安地区。每套房源均经实地核实，每位业主均经过审核，每位买家从首次看房到过户均获得全程陪同。",
    footer_rights: "版权所有。",
    final_cta_title: "准备好在华欣寻找您的理想住宅了吗？", footer_tagline: "专注华欣、巴蓝武里与差安的精品房地产公司。", footer_explore: "浏览", footer_company: "公司", footer_contact: "联系方式",
    share_site: "分享本站", copy_link: "复制链接", link_copied: "已复制！",
    login_signup: "登录 / 注册", bd_short: "卧室", ba_short: "浴室", properties_saved: "个房源已收藏", property_saved: "个房源已收藏",
    trust_local_title: "华欣本地专业知识", trust_local_desc: "扎根于华欣、巴蓝武里和差安的精品地产公司。",
    trust_verified_title: "已核实房源", trust_verified_desc: "每套房源在发布前均经过实地检查和核实。",
    trust_lang_title: "多语言服务", trust_lang_desc: "支持泰语、英语、俄语、中文等多种语言。",
    trust_contact_title: "直接联系", trust_contact_desc: "通过LINE、WhatsApp或电话直接联系经纪人——无需客服中心。",
    listings_count: "套房源",
    sort_label: "排序", sort_newest: "最新发布", sort_price_asc: "价格：从低到高", sort_price_desc: "价格：从高到低",
    view_grid: "网格视图", view_list: "列表视图",
    filters: "筛选", apply_filters: "应用筛选", clear_filters: "清除",
    keyword_label: "关键词或房源编号", keyword_placeholder: "例如 HH-101 或 泳池别墅",
    gallery_tab_photos: "照片", gallery_tab_video: "视频导览", gallery_tab_360: "360° 全景", coming_soon: "即将推出",
    reviews_title: "客户评价", no_reviews: "暂无评价", reviews_unit: "条评价", reviews_sample_note: "示例数据",
    no_reviews_placeholder: "暂无评价 — 此区域将在未来版本中用于评价系统。",
    mortgage_calc_title: "房贷计算器", mortgage_down_payment: "首付款", mortgage_loan_years: "贷款年限", years_unit: "年",
    mortgage_interest_rate: "利率", mortgage_monthly_payment: "预计月供",
    mortgage_disclaimer: "这只是初步估算（仅本金+利息，不含费用/保险），并非真实贷款报价。",
    schedule_viewing_title: "预约看房",
    bedrooms_label: "卧室数", bathrooms_label: "卫浴数", land_size_label: "地块面积", living_area_label: "使用面积", any: "不限",
    status_label: "状态", features_label: "特色设施",
    no_results: "没有符合筛选条件的房源。",
    sqm: "平方米", per_month: "/ 月",
    km_to: "公里至", mini_site_label: "个人网站",
    beach: "海滩", town: "市中心",
    gallery_photo: "照片",
    property_overview: "概览", property_description: "详细描述", no_description: "暂无描述。", property_features: "特色与设施", property_location: "位置", property_general_area: "大致区域", similar_properties: "相似房源",
    contact_agent: "联系经纪人", enquiry_form: "发送咨询", name_label: "姓名", email_label: "邮箱", phone_label: "电话", message_label: "留言", send: "发送咨询",
    call: "致电", whatsapp: "WhatsApp", line_app: "Line", email_cta: "邮箱",
    sell_title: "委托出售/出租房产", sell_sub: "告诉我们您的房产信息——出售或出租——我们的团队将在24小时内与您联系。",
    sell_owner_name: "您的姓名", sell_owner_phone: "电话", sell_owner_email: "邮箱", sell_owner_line: "Line ID（可选）",
    sell_property_type: "房产类型", sell_listing_type: "委托类型", sell_area: "地区", sell_price: "期望价格", sell_notes: "补充说明",
    sell_submit: "提交房产信息",
    contact_title: "联系我们", contact_sub: "关于在华欣、巴蓝武里或差安买房、租房或委托出售有疑问？我们随时为您解答。",
    admin_login_title: "管理员登录", admin_username: "用户名", admin_password: "密码", admin_login_cta: "登录",
    admin_dashboard: "仪表盘", admin_listings: "房源列表", admin_total: "房源总数", admin_for_sale: "出售中", admin_for_rent: "出租中", admin_sold: "已售", admin_reserved: "已预订", admin_new: "本月新增",
    admin_add_property: "添加房源", admin_edit: "编辑", admin_delete: "删除", admin_search: "搜索房源...",
    admin_owner_info: "业主信息（仅内部）", admin_internal_notes: "内部备注", admin_photos: "照片", admin_set_cover: "设为封面", admin_save: "保存更改", admin_saving: "保存中...", admin_save_success: "保存成功", admin_photos_note: "照片上传后会立即保存，无需等待点击保存更改。", admin_cancel: "取消",
    admin_logout: "退出登录", admin_signed_in_as: "以管理员身份登录",
    admin_field_title: "标题", admin_field_zone: "区域", admin_field_price: "价格（泰铢）",
    admin_field_land_size: "地块面积（平方米）", admin_field_living_area: "使用面积（平方米）",
    admin_field_parking: "停车位", admin_field_ownership: "产权",
    admin_field_distance_beach: "距海滩距离（公里）", admin_field_distance_town: "距市中心距离（公里）",
    admin_field_pool: "游泳池", admin_field_furnished: "家具配置",
    admin_furnished_full: "全套家具", admin_furnished_partial: "部分家具", admin_furnished_none: "无家具",
    admin_field_short_desc: "简短描述", admin_field_full_desc: "详细描述",
    admin_add_photo: "+ 添加照片位", admin_owner_disclaimer: "不对外公开",
    admin_owner_name_ph: "业主姓名", admin_owner_phone_ph: "业主电话", admin_owner_email_ph: "业主邮箱", admin_owner_line_ph: "业主 Line ID",
    admin_owner_notes_ph: "关于业主的私密备注",
    admin_owners_nav: "联系人", admin_owners_title: "业主名录", admin_owners_sub: "所有业主及其委托给我们的房源——仅限管理员查看的私密信息。",
    admin_owner_properties: "委托房源", admin_view_on_map: "查看地图", admin_view_edit_property: "查看/编辑房源",
    admin_back_to_dashboard: "← 返回仪表盘", admin_new_owner: "+ 新增业主", admin_owner_select: "业主",
    admin_owner_photo1: "业主照片 / 证件", admin_owner_photo2: "联系方式截图", admin_map_link: "地图链接（Google Maps URL）",
    admin_tenant_photo1: "租客照片 / 证件", admin_tenant_photo2: "联系方式截图",
    admin_rented: "已出租中", admin_lease_ends: "租约到期", admin_days_left: "天后到期", admin_tenant: "租客",
    admin_showing_rented: "显示已出租房源，按租约到期日由近到远排序", admin_clear_view: "✕ 清除筛选",
    status_rented: "已出租（有租客）", admin_lease_start: "起租日", admin_lease_end: "租约到期日",
    admin_tenant_info: "租客信息", admin_tenant_select: "租客", admin_new_tenant: "+ 新增租客",
    admin_tenant_name_ph: "租客姓名", admin_tenant_phone_ph: "租客电话", admin_tenant_email_ph: "租客邮箱", admin_tenant_line_ph: "租客 Line ID", admin_tenant_notes_ph: "关于租客的备注",
    contacts_title: "联系人名录", contacts_sub: "业主、租客及其关联的所有房源——仅限管理员查看的私密信息。",
    contacts_tab_owners: "业主", contacts_tab_tenants: "租客", admin_lease_ends_col: "租约到期",
    admin_map_title: "房源地图", admin_map_sub: "浏览华欣、巴蓝武里及差安的实时地图，然后点击下方任何房源即可在地图上查看或打开编辑。", admin_map_note: "以上为真实的 Google 地图嵌入（本原型未配置自定义图钉所需的 API 密钥）—请使用下方按类型着色的列表浏览并点击进入房源。", admin_map_nav: "地图",
  },
  fr: {
    site_name: "huahin.properties",
    nav_buy: "Acheter", nav_rent: "Louer", nav_sell: "Vendre / Confier", nav_about: "À propos", nav_contact: "Contact", nav_admin: "Admin",
    hero_kicker: "Hua Hin · Pranburi · Cha-am",
    hero_title_1: "Vivre sur la côte,", hero_title_2: "luxe discret.",
    hero_sub: "Villas avec piscine, maisons de bord de mer et terrains sélectionnés le long de la côte royale de Thaïlande — pour acheteurs, locataires et propriétaires exigeants.",
    want_label: "Je souhaite", buy: "Acheter", rent: "Louer",
    location_label: "Emplacement", all_zones: "Toutes les zones",
    type_label: "Type de bien", any_type: "Tous types",
    budget_label: "Budget", any_price: "Tous les prix",
    search_cta: "Rechercher des biens",
    cta_find: "Trouvez votre maison", cta_buy: "Acheter un bien", cta_rent: "Louer un bien", cta_list: "Confier un bien", cta_contact: "Contacter un agent",
    featured_title: "Biens en vedette", featured_sub: "Une sélection soignée le long de la côte",
    view_details: "Voir les détails",
    areas_title: "Explorer par zone",
    area_hua_hin_desc: "La ville côtière royale d'origine de la Thaïlande — plages, golf et la gare historique.",
    area_pranburi_desc: "Larges plages de sable et terrains paisibles, prisés pour les résidences privées.",
    area_cha_am_desc: "Une ville balnéaire décontractée à forte demande locative et facilement accessible depuis Bangkok.",
    about_title: "Pourquoi huahin.properties",
    about_body: "Nous sommes une agence boutique basée à Hua Hin, opérant exclusivement à Hua Hin, Pranburi et Cha-am. Chaque annonce est vérifiée en personne, chaque propriétaire est validé, et chaque acheteur est accompagné de la première visite jusqu'à la signature du chanote.",
    footer_rights: "Tous droits réservés.",
    final_cta_title: "Prêt à trouver votre maison à Hua Hin ?", footer_tagline: "Une agence immobilière boutique pour Hua Hin, Pranburi et Cha-am.", footer_explore: "Explorer", footer_company: "Société", footer_contact: "Contact",
    share_site: "Partager ce site", copy_link: "Copier le lien", link_copied: "Lien copié !",
    login_signup: "Connexion / Inscription", bd_short: "ch.", ba_short: "sdb", properties_saved: "biens enregistrés", property_saved: "bien enregistré",
    trust_local_title: "Expertise locale à Hua Hin", trust_local_desc: "Agence boutique implantée à Hua Hin, Pranburi et Cha-am.",
    trust_verified_title: "Annonces vérifiées", trust_verified_desc: "Chaque bien est inspecté et vérifié en personne avant publication.",
    trust_lang_title: "Service multilingue", trust_lang_desc: "Support en thaï, anglais, russe, chinois et plus encore.",
    trust_contact_title: "Contact direct", trust_contact_desc: "Contactez un agent directement via LINE, WhatsApp ou téléphone — sans centre d'appels.",
    listings_count: "annonces",
    sort_label: "Trier", sort_newest: "Plus récent", sort_price_asc: "Prix : croissant", sort_price_desc: "Prix : décroissant",
    view_grid: "Grille", view_list: "Liste",
    filters: "Filtres", apply_filters: "Appliquer les filtres", clear_filters: "Réinitialiser",
    keyword_label: "Mot-clé ou code du bien", keyword_placeholder: "ex. HH-101 ou villa avec piscine",
    gallery_tab_photos: "Photos", gallery_tab_video: "Visite vidéo", gallery_tab_360: "Visite 360°", coming_soon: "bientôt disponible",
    reviews_title: "Avis clients", no_reviews: "Aucun avis pour le moment", reviews_unit: "avis", reviews_sample_note: "données d'exemple",
    no_reviews_placeholder: "Aucun avis pour le moment — cet espace est réservé au système d'avis dans une future version.",
    mortgage_calc_title: "Calculateur de prêt", mortgage_down_payment: "Acompte", mortgage_loan_years: "Durée du prêt", years_unit: "ans",
    mortgage_interest_rate: "Taux d'intérêt", mortgage_monthly_payment: "Mensualité estimée",
    mortgage_disclaimer: "Estimation de base (capital + intérêts uniquement, hors frais/assurance) — pas une offre de prêt réelle.",
    schedule_viewing_title: "Planifier une visite",
    bedrooms_label: "Chambres", bathrooms_label: "Salles de bain", land_size_label: "Superficie du terrain", living_area_label: "Surface habitable", any: "Indifférent",
    status_label: "Statut", features_label: "Équipements",
    no_results: "Aucun bien ne correspond à vos filtres.",
    sqm: "m²", per_month: "/ mois",
    km_to: "km jusqu'à", mini_site_label: "Mini-site",
    beach: "Plage", town: "Ville",
    gallery_photo: "Photo",
    property_overview: "Aperçu", property_description: "Description", no_description: "Aucune description pour le moment.", property_features: "Équipements & prestations", property_location: "Emplacement", property_general_area: "Zone approximative", similar_properties: "Biens similaires",
    contact_agent: "Contacter un agent", enquiry_form: "Envoyer une demande", name_label: "Nom", email_label: "E-mail", phone_label: "Téléphone", message_label: "Message", send: "Envoyer la demande",
    call: "Appeler", whatsapp: "WhatsApp", line_app: "Line", email_cta: "E-mail",
    sell_title: "Confier un bien", sell_sub: "Parlez-nous de votre bien — à vendre ou à louer — et notre équipe vous contactera sous 24 heures.",
    sell_owner_name: "Votre nom", sell_owner_phone: "Téléphone", sell_owner_email: "E-mail", sell_owner_line: "Identifiant Line (facultatif)",
    sell_property_type: "Type de bien", sell_listing_type: "Type d'annonce", sell_area: "Zone", sell_price: "Prix souhaité", sell_notes: "Plus de détails",
    sell_submit: "Soumettre le bien",
    contact_title: "Contactez-nous", contact_sub: "Des questions sur l'achat, la location ou la mise en vente à Hua Hin, Pranburi ou Cha-am ? Nous sommes là pour vous aider.",
    admin_login_title: "Connexion admin", admin_username: "Nom d'utilisateur", admin_password: "Mot de passe", admin_login_cta: "Se connecter",
    admin_dashboard: "Tableau de bord", admin_listings: "Annonces", admin_total: "Total des annonces", admin_for_sale: "À vendre", admin_for_rent: "À louer", admin_sold: "Vendu", admin_reserved: "Réservé", admin_new: "Nouveau ce mois-ci",
    admin_add_property: "Ajouter un bien", admin_edit: "Modifier", admin_delete: "Supprimer", admin_search: "Rechercher des annonces...",
    admin_owner_info: "Informations du propriétaire (privé)", admin_internal_notes: "Notes internes", admin_photos: "Photos", admin_set_cover: "Définir comme couverture", admin_save: "Enregistrer les modifications", admin_saving: "Enregistrement…", admin_save_success: "Enregistré avec succès", admin_photos_note: "Les photos sont enregistrées dès leur envoi — inutile d'attendre pour enregistrer.", admin_cancel: "Annuler",
    admin_logout: "Déconnexion", admin_signed_in_as: "Connecté en tant qu'admin",
    admin_field_title: "Titre", admin_field_zone: "Zone", admin_field_price: "Prix (THB)",
    admin_field_land_size: "Superficie du terrain (m²)", admin_field_living_area: "Surface habitable (m²)",
    admin_field_parking: "Places de parking", admin_field_ownership: "Type de propriété",
    admin_field_distance_beach: "Distance de la plage (km)", admin_field_distance_town: "Distance de la ville (km)",
    admin_field_pool: "Piscine", admin_field_furnished: "Meublé",
    admin_furnished_full: "Entièrement meublé", admin_furnished_partial: "Partiellement meublé", admin_furnished_none: "Non meublé",
    admin_field_short_desc: "Description courte", admin_field_full_desc: "Description complète",
    admin_add_photo: "+ Ajouter un emplacement photo", admin_owner_disclaimer: "jamais affiché publiquement",
    admin_owner_name_ph: "Nom du propriétaire", admin_owner_phone_ph: "Téléphone du propriétaire", admin_owner_email_ph: "E-mail du propriétaire", admin_owner_line_ph: "Identifiant Line du propriétaire",
    admin_owner_notes_ph: "Notes privées sur le propriétaire",
    admin_owners_nav: "Contacts", admin_owners_title: "Registre des propriétaires", admin_owners_sub: "Chaque propriétaire et chaque bien qu'il nous a confié — privé, réservé à l'admin.",
    admin_owner_properties: "Biens", admin_view_on_map: "Voir sur la carte", admin_view_edit_property: "Voir / modifier le bien",
    admin_back_to_dashboard: "← Retour au tableau de bord", admin_new_owner: "+ Nouveau propriétaire", admin_owner_select: "Propriétaire",
    admin_owner_photo1: "Photo / pièce d'identité du propriétaire", admin_owner_photo2: "Capture d'écran du contact", admin_map_link: "Lien de carte (URL Google Maps)",
    admin_tenant_photo1: "Photo / pièce d'identité du locataire", admin_tenant_photo2: "Capture d'écran du contact",
    admin_rented: "Actuellement loué", admin_lease_ends: "Fin du bail", admin_days_left: "jours restants", admin_tenant: "Locataire",
    admin_showing_rented: "Affichage des biens loués, fin de bail la plus proche en premier", admin_clear_view: "✕ Réinitialiser",
    status_rented: "Loué (occupé)", admin_lease_start: "Début du bail", admin_lease_end: "Fin du bail",
    admin_tenant_info: "Informations sur le locataire", admin_tenant_select: "Locataire", admin_new_tenant: "+ Nouveau locataire",
    admin_tenant_name_ph: "Nom du locataire", admin_tenant_phone_ph: "Téléphone du locataire", admin_tenant_email_ph: "E-mail du locataire", admin_tenant_line_ph: "Identifiant Line du locataire", admin_tenant_notes_ph: "Notes sur le locataire",
    contacts_title: "Registre des contacts", contacts_sub: "Propriétaires, locataires et tous les biens qui leur sont liés — privé, réservé à l'admin.",
    contacts_tab_owners: "Propriétaires", contacts_tab_tenants: "Locataires", admin_lease_ends_col: "Fin du bail",
    admin_map_title: "Carte des biens", admin_map_sub: "Parcourez la carte en direct de Hua Hin, Pranburi et Cha-am, puis cliquez sur une annonce ci-dessous pour la voir sur la carte ou l'ouvrir en édition.", admin_map_note: "Véritable intégration Google Maps ci-dessus (aucune clé API configurée pour les repères personnalisés dans ce prototype) — utilisez la liste codée par couleur ci-dessous pour parcourir par type et accéder aux annonces.", admin_map_nav: "Carte",
  },
  it: {
    site_name: "huahin.properties",
    nav_buy: "Acquista", nav_rent: "Affitta", nav_sell: "Vendi / Affida", nav_about: "Chi siamo", nav_contact: "Contatti", nav_admin: "Admin",
    hero_kicker: "Hua Hin · Pranburi · Cha-am",
    hero_title_1: "Vivere sulla costa,", hero_title_2: "lusso discreto.",
    hero_sub: "Ville con piscina, case sul mare e terreni selezionati lungo la costa reale della Thailandia — per acquirenti, affittuari e proprietari che pretendono di più.",
    want_label: "Voglio", buy: "Acquistare", rent: "Affittare",
    location_label: "Posizione", all_zones: "Tutte le zone",
    type_label: "Tipo di immobile", any_type: "Tutti i tipi",
    budget_label: "Budget", any_price: "Qualsiasi prezzo",
    search_cta: "Cerca immobili",
    cta_find: "Trova la tua casa", cta_buy: "Acquista un immobile", cta_rent: "Affitta un immobile", cta_list: "Affida un immobile", cta_contact: "Contatta un agente",
    featured_title: "Immobili in evidenza", featured_sub: "Una selezione curata lungo la costa",
    view_details: "Vedi dettagli",
    areas_title: "Esplora per zona",
    area_hua_hin_desc: "La città costiera reale originaria della Thailandia — spiagge, golf e la storica stazione ferroviaria.",
    area_pranburi_desc: "Ampie spiagge sabbiose e terreni tranquilli, apprezzati per residenze private.",
    area_cha_am_desc: "Una rilassata città balneare con forte domanda di affitti e facili collegamenti con Bangkok.",
    about_title: "Perché huahin.properties",
    about_body: "Siamo un'agenzia boutique con sede a Hua Hin, operativa esclusivamente a Hua Hin, Pranburi e Cha-am. Ogni annuncio viene verificato di persona, ogni proprietario controllato, e ogni acquirente seguito dalla prima visita fino alla firma del chanote.",
    footer_rights: "Tutti i diritti riservati.",
    final_cta_title: "Pronti a trovare casa a Hua Hin?", footer_tagline: "Un'agenzia immobiliare boutique per Hua Hin, Pranburi e Cha-am.", footer_explore: "Esplora", footer_company: "Azienda", footer_contact: "Contatti",
    share_site: "Condividi il sito", copy_link: "Copia link", link_copied: "Link copiato!",
    login_signup: "Accedi / Registrati", bd_short: "cam.", ba_short: "bagni", properties_saved: "immobili salvati", property_saved: "immobile salvato",
    trust_local_title: "Esperienza locale a Hua Hin", trust_local_desc: "Agenzia boutique presente sul posto a Hua Hin, Pranburi e Cha-am.",
    trust_verified_title: "Annunci verificati", trust_verified_desc: "Ogni immobile viene ispezionato e verificato di persona prima della pubblicazione.",
    trust_lang_title: "Servizio multilingue", trust_lang_desc: "Supporto in thailandese, inglese, russo, cinese e altro.",
    trust_contact_title: "Contatto diretto", trust_contact_desc: "Contatta direttamente un agente via LINE, WhatsApp o telefono — senza call center.",
    listings_count: "annunci",
    sort_label: "Ordina", sort_newest: "Più recenti", sort_price_asc: "Prezzo: crescente", sort_price_desc: "Prezzo: decrescente",
    view_grid: "Griglia", view_list: "Elenco",
    filters: "Filtri", apply_filters: "Applica filtri", clear_filters: "Reimposta",
    keyword_label: "Parola chiave o codice immobile", keyword_placeholder: "es. HH-101 o villa con piscina",
    gallery_tab_photos: "Foto", gallery_tab_video: "Video tour", gallery_tab_360: "Tour 360°", coming_soon: "in arrivo",
    reviews_title: "Recensioni dei clienti", no_reviews: "Ancora nessuna recensione", reviews_unit: "recensioni", reviews_sample_note: "dati di esempio",
    no_reviews_placeholder: "Ancora nessuna recensione — questo spazio è riservato al sistema di recensioni in una versione futura.",
    mortgage_calc_title: "Calcolatore mutuo", mortgage_down_payment: "Acconto", mortgage_loan_years: "Durata prestito", years_unit: "anni",
    mortgage_interest_rate: "Tasso d'interesse", mortgage_monthly_payment: "Rata mensile stimata",
    mortgage_disclaimer: "Questa è una stima di base (solo capitale + interessi, escluse commissioni/assicurazione) — non è un'offerta di prestito reale.",
    schedule_viewing_title: "Prenota una visita",
    bedrooms_label: "Camere da letto", bathrooms_label: "Bagni", land_size_label: "Superficie del terreno", living_area_label: "Superficie abitabile", any: "Indifferente",
    status_label: "Stato", features_label: "Caratteristiche",
    no_results: "Nessun immobile corrisponde ai tuoi filtri.",
    sqm: "m²", per_month: "/ mese",
    km_to: "km da", mini_site_label: "Mini sito",
    beach: "Spiaggia", town: "Città",
    gallery_photo: "Foto",
    property_overview: "Panoramica", property_description: "Descrizione", no_description: "Nessuna descrizione ancora disponibile.", property_features: "Caratteristiche e servizi", property_location: "Posizione", property_general_area: "Zona approssimativa", similar_properties: "Immobili simili",
    contact_agent: "Contatta un agente", enquiry_form: "Invia una richiesta", name_label: "Nome", email_label: "E-mail", phone_label: "Telefono", message_label: "Messaggio", send: "Invia richiesta",
    call: "Chiama", whatsapp: "WhatsApp", line_app: "Line", email_cta: "E-mail",
    sell_title: "Affida un immobile", sell_sub: "Raccontaci del tuo immobile — in vendita o in affitto — e il nostro team ti contatterà entro 24 ore.",
    sell_owner_name: "Il tuo nome", sell_owner_phone: "Telefono", sell_owner_email: "E-mail", sell_owner_line: "ID Line (facoltativo)",
    sell_property_type: "Tipo di immobile", sell_listing_type: "Tipo di annuncio", sell_area: "Zona", sell_price: "Prezzo desiderato", sell_notes: "Maggiori dettagli",
    sell_submit: "Invia immobile",
    contact_title: "Contattaci", contact_sub: "Domande su acquisto, affitto o messa in vendita a Hua Hin, Pranburi o Cha-am? Siamo qui per aiutarti.",
    admin_login_title: "Accesso admin", admin_username: "Nome utente", admin_password: "Password", admin_login_cta: "Accedi",
    admin_dashboard: "Dashboard", admin_listings: "Annunci", admin_total: "Totale annunci", admin_for_sale: "In vendita", admin_for_rent: "In affitto", admin_sold: "Venduto", admin_reserved: "Riservato", admin_new: "Nuovi questo mese",
    admin_add_property: "Aggiungi immobile", admin_edit: "Modifica", admin_delete: "Elimina", admin_search: "Cerca annunci...",
    admin_owner_info: "Dati del proprietario (privato)", admin_internal_notes: "Note interne", admin_photos: "Foto", admin_set_cover: "Imposta come copertina", admin_save: "Salva modifiche", admin_saving: "Salvataggio…", admin_save_success: "Salvato con successo", admin_photos_note: "Le foto vengono salvate subito dopo il caricamento — non serve attendere per salvare.", admin_cancel: "Annulla",
    admin_logout: "Esci", admin_signed_in_as: "Accesso effettuato come admin",
    admin_field_title: "Titolo", admin_field_zone: "Zona", admin_field_price: "Prezzo (THB)",
    admin_field_land_size: "Superficie del terreno (m²)", admin_field_living_area: "Superficie abitabile (m²)",
    admin_field_parking: "Posti auto", admin_field_ownership: "Tipo di proprietà",
    admin_field_distance_beach: "Distanza dalla spiaggia (km)", admin_field_distance_town: "Distanza dalla città (km)",
    admin_field_pool: "Piscina", admin_field_furnished: "Arredato",
    admin_furnished_full: "Completamente arredato", admin_furnished_partial: "Parzialmente arredato", admin_furnished_none: "Non arredato",
    admin_field_short_desc: "Descrizione breve", admin_field_full_desc: "Descrizione completa",
    admin_add_photo: "+ Aggiungi spazio foto", admin_owner_disclaimer: "mai mostrato pubblicamente",
    admin_owner_name_ph: "Nome del proprietario", admin_owner_phone_ph: "Telefono del proprietario", admin_owner_email_ph: "E-mail del proprietario", admin_owner_line_ph: "ID Line del proprietario",
    admin_owner_notes_ph: "Note private sul proprietario",
    admin_owners_nav: "Contatti", admin_owners_title: "Registro proprietari", admin_owners_sub: "Ogni proprietario e ogni immobile che ci ha affidato — privato, solo per admin.",
    admin_owner_properties: "Immobili", admin_view_on_map: "Vedi sulla mappa", admin_view_edit_property: "Vedi / modifica immobile",
    admin_back_to_dashboard: "← Torna alla dashboard", admin_new_owner: "+ Nuovo proprietario", admin_owner_select: "Proprietario",
    admin_owner_photo1: "Foto / documento del proprietario", admin_owner_photo2: "Screenshot del contatto", admin_map_link: "Link mappa (URL Google Maps)",
    admin_tenant_photo1: "Foto / documento dell'inquilino", admin_tenant_photo2: "Screenshot del contatto",
    admin_rented: "Attualmente affittato", admin_lease_ends: "Fine contratto", admin_days_left: "giorni rimanenti", admin_tenant: "Inquilino",
    admin_showing_rented: "Visualizzazione immobili affittati, scadenza più vicina per prima", admin_clear_view: "✕ Reimposta",
    status_rented: "Affittato (occupato)", admin_lease_start: "Inizio contratto", admin_lease_end: "Fine contratto",
    admin_tenant_info: "Informazioni sull'inquilino", admin_tenant_select: "Inquilino", admin_new_tenant: "+ Nuovo inquilino",
    admin_tenant_name_ph: "Nome dell'inquilino", admin_tenant_phone_ph: "Telefono dell'inquilino", admin_tenant_email_ph: "E-mail dell'inquilino", admin_tenant_line_ph: "ID Line dell'inquilino", admin_tenant_notes_ph: "Note sull'inquilino",
    contacts_title: "Registro contatti", contacts_sub: "Proprietari, inquilini e tutti gli immobili a loro collegati — privato, solo per admin.",
    contacts_tab_owners: "Proprietari", contacts_tab_tenants: "Inquilini", admin_lease_ends_col: "Fine contratto",
    admin_map_title: "Mappa degli immobili", admin_map_sub: "Sfoglia la mappa dal vivo di Hua Hin, Pranburi e Cha-am, poi clicca su un annuncio qui sotto per vederlo sulla mappa o modificarlo.", admin_map_note: "Vera integrazione di Google Maps sopra (nessuna chiave API configurata per pin personalizzati in questo prototipo) — usa l'elenco codificato a colori qui sotto per sfogliare per tipo e accedere agli annunci.", admin_map_nav: "Mappa",
  },
};


export const TENANTS = [
];

export const OWNERS = [
];

export function formatPrice(price, currency, lang) {
  const n = Number(price).toLocaleString(lang === "th" ? "th-TH" : lang === "ru" ? "ru-RU" : lang === "zh" ? "zh-CN" : "en-US");
  return `฿${n}`;
}

// Admin edits (status, price, photos, features, etc.) are saved into localStorage
// by Admin Dashboard / Owners as flat single-language records. Public-facing pages
// (Home, Search Results, Property Details) call this to merge those edits on top of
// the static multi-language PROPERTIES, so anything an admin changes — including the
// photo gallery — is reflected on the public site immediately.
export const ADMIN_DATA_VERSION = "4";

export const OWNERSHIP_LABELS = {
  "Chanote": { en: "Chanote (freehold title)", th: "โฉนดที่ดิน (กรรมสิทธิ์เต็ม)", ru: "Чанот (право собственности)", zh: "查诺特地契（完全产权）", de: "Chanote (Eigentumsurkunde)", no: "Chanote (eiendomsrett)", fr: "Chanote (pleine propriété)", it: "Chanote (piena proprietà)" },
  "Foreign Freehold Quota": { en: "Foreign Freehold Quota", th: "โควตากรรมสิทธิ์ต่างชาติ", ru: "Иностранная квота на право собственности", zh: "外国人产权配额", de: "Ausländer-Eigentumsquote", no: "Utenlandsk eierkvote", fr: "Quota de pleine propriété étrangère", it: "Quota di proprietà per stranieri" },
  "N/A (Rental)": { en: "N/A (Rental)", th: "ไม่เกี่ยวข้อง (บ้านเช่า)", ru: "Не применимо (аренда)", zh: "不适用（出租）", de: "N/V (Miete)", no: "Ikke aktuelt (leie)", fr: "N/A (Location)", it: "N/D (Affitto)" },
};

export function ownershipLabel(raw, lang) {
  if (!raw) return raw;
  const entry = OWNERSHIP_LABELS[raw];
  return entry ? (entry[lang] || entry.en) : raw;
}

export function getEffectivePropertiesSync(mod) {
  return mod.PROPERTIES;
}

// Real, shared version: fetches the current property list from Firebase
// (so every visitor sees the same admin-edited data + uploaded photos),
// falling back to the static bundled sample data if Firebase is
// unreachable. This replaces the old localStorage-based merge above, which
// only ever reflected edits made in that one browser.
export async function getEffectiveProperties(mod) {
  try {
    const fb = await import("./firebase-client.js");
    const [properties, allPhotos] = await Promise.all([
      fb.fetchCollection("properties"),
      fb.fetchAllPhotos(),
    ]);
    if (!properties || !properties.length) return mod.PROPERTIES;
    // "live" is the only publicly-visible state under the trial/expiry/
    // approval model (pending/expired/rejected all hidden). Listings saved
    // before this model existed have no listingStatus field at all — treat
    // those as grandfathered-live as long as they were already published
    // (!isDraft), so nothing already-live silently disappears.
    const visible = properties.filter((p) => p.listingStatus === "live" || (p.listingStatus === undefined && !p.isDraft));
    const photosById = {};
    allPhotos.forEach((ph) => { photosById[ph.id] = ph.dataUrl; });
    const fromFirestore = visible.map((p) => {
      const photos = (p.photos || []).map((ph, i) => {
        const label = typeof ph === "string" ? ph : ph.label;
        const url = photosById[`${p.id}-${i}`] || (typeof ph === "object" && ph.url) || "";
        return { label, url };
      });
      // Brand-new properties added via Admin only have a single-language
      // string for title/shortDesc/fullDesc — wrap them so the rest of the
      // site (which expects { en, th, ru, zh }) still works.
      const wrap = (v) => (v && typeof v === "object" ? v : { en: v, th: v, ru: v, zh: v });
      return {
        ...p, photos, title: wrap(p.title), shortDesc: wrap(p.shortDesc), fullDesc: wrap(p.fullDesc),
        // Self-serve listings (Lister Dashboard) don't collect these fields
        // yet — default them so pages that assume they're always arrays/
        // numbers (feature filters, distance display) don't crash.
        features: p.features || [], distanceBeach: p.distanceBeach || 0, distanceTown: p.distanceTown || 0,
      };
    });
    // CRITICAL: the bundled sample catalog (mod.PROPERTIES — HH-101, CA-301,
    // etc.) must stay visible even after Firestore has real data, otherwise
    // every demo listing silently vanishes site-wide (Home/Search/Property
    // Details) the moment even ONE real self-serve listing exists — this
    // was happening because the code used to RETURN ONLY the Firestore
    // results once Firestore was non-empty, never merging in the bundled
    // catalog. Firestore is the source of truth for any id it already has
    // (an admin/seed doc may have been edited there); any bundled sample id
    // NOT present in Firestore at all is appended as-is.
    const firestoreIds = new Set(properties.map((p) => p.id));
    const staticOnly = (mod.PROPERTIES || []).filter((p) => !firestoreIds.has(p.id));
    return [...fromFirestore, ...staticOnly];
  } catch (e) {
    console.warn("getEffectiveProperties: Firebase fetch failed, using bundled sample data:", e);
    return mod.PROPERTIES;
  }
}
